### ISSUE TITLE
DLS: Visual Styling - Branding Standards - Background Patterns

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#206]
Seems like some are getting cut off and can't see text. There might be a better way to display it.

**Comment by garza-utsa** [comment]
we can adopt/reuse what @Uri-E implements for the color standards here, adding to todo for now

**Comment by garza-utsa** [comment]
@Uri-E , please apply the same html you used for the colors here as well, thanks!

**Comment by garza-utsa** [comment]
https://utsa-asc.github.io/college-dls/components/detail/background-patterns.html

**Comment by garza-utsa** [comment]
closed by #239
