### ISSUE TITLE
DLS: Branding Standards - Typography - Intro - Additional Variants

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#208]
Note states:

Notes from Simpson Scarborough Implementation
More color variations may need to be developed in the future.

https://utsa-asc.github.io/college-dls/components/detail/intro.html

**Comment by garza-utsa** [comment]
I don't think this is currently used anywhere, but it was intended as a page topper/header block for opening statements on a page.

It would be useful to at least have a default (white bg) and alternate variant (grey bg), an example usage of this in cascade (but currently not implemented) is on the sds opening statement right below the banner:

https://sdstest.utsa.edu

Kinda overkill to implement this as a pure component in cascade, but maybe expose it as a class that can be used in the formats menu via the editor config in cascade?
