### ISSUE TITLE
DLS: Components - Card - Profile - Default

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#221]
The documentation states the following: 
_TODO: Create a separate preview template for this component to pop into a col-3 or col-4 width size._

https://utsa-asc.github.io/college-dls/components/detail/profile-card--default.html

**Comment by garza-utsa** [comment]
more info on the todo, this was before we added the section level components, we should instead create a section component for a group of profile cards, there is an example of one variant here:

https://utsa-asc.github.io/college-dls/components/detail/department-secondary-page--default.html

we we did codify in a new faculty listing page:

https://utsa-asc.github.io/college-dls/components/detail/faculty-listing-page.html

The larger faculty-bio has a multiple example on the institute secondary page:
https://utsa-asc.github.io/college-dls/components/detail/institute-secondary-page.html

But there is no example of using multiple Profile - Default cards on one page (if this is an option).  More discussion needed =)

**Comment by lalov1** [comment]
I think adding a section component for a group of profile cards will work. Also, I noticed the profile card list is a little tight:
![Image](https://user-images.githubusercontent.com/7785251/173145375-70486d37-19c3-4110-8af8-13898f910009.png)

It looks like there is some code for lower breakpoints, so maybe we could expand this to cover large breakpoints:
````
@media (max-width: 991px) {
	.profile-card-list .row>div {
		margin-bottom: 20px;
	}
}
````

**Comment by garza-utsa** [comment]
should this type of dynamic spacing live more on the <section> level so it works consistently between all type of section components?

**Comment by lalov1** [comment]
yep, that should work!

**Comment by prd409-utsa** [comment]
I finished all my accordion tasks so taking this one!

**Comment by prd409-utsa** [comment]
This was done as a section/content-group/profile-group last week, so closing this issue.

[https://utsa-asc.github.io/college-dls/components/detail/profile-group.html](https://utsa-asc.github.io/college-dls/components/detail/profile-group.html)
