### ISSUE TITLE
DLS: Components - Profile - Contact Callout - Default

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#222]
The documentation states the following: 
_TODO: Create a separate preview template for this component to pop into a col-3 or col-4 width size._

A couple of spelling errors in the code: 

- ```staff-card-componet-div```
- ```staff-card-deoartment```
Didn't know if I update and if it would break anything, so I didn't update. 

Missing SCSS as well.

**Comment by garza-utsa** [comment]
definitely typos from the vendor, nobody from us would misspell stuff that horribly >.>

**Comment by garza-utsa** [comment]
fixed by #245
