### ISSUE TITLE
DLS: Section Components - Accordion - Issues

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#226]
It seems like when you open an accordion the title disappears and if you open both there are some issues closing them. 

![Image](https://user-images.githubusercontent.com/7785251/170127047-3d6b99cc-ad98-47bf-bc04-4ba4920a6c39.png)

**Comment by garza-utsa** [comment]
duplicate of #193

**Comment by prd409-utsa** [comment]
This was fixed in [PR 314](https://github.com/utsa-asc/college-dls/pull/314)
