### ISSUE TITLE
DLS: Section Components - Call To Action Buttons - Multi Color

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#228]
Should this be two different colors?

**Comment by garza-utsa** [comment]
Discussion needed on this, this was stubbed out with the intent of two different color buttons, not in the original deliverables, but I stopped after thinking about what that would mean in a orange and blue background.  Should we not support it at all?  Or only support orange/blue multi buttons on grey/white background?

**Comment by Uri-E** [comment]
Hmm, I think we'd have to limit it to use with grey/white backgrounds. Otherwise I can see how getting it to work with color backgrounds could get ridiculous.

**Comment by garza-utsa** [comment]
yeah, if we support multiple color buttons, I think we would have to place the restriction that this only be supported on white or grey background colors.  That could be a mess to enforce...but I'm open to having a new variant for this explicit use case (as long as we add that restriction to the documentation).  I can see the visual value of having one button stand out from another

**Comment by garza-utsa** [comment]
going to close this for now as not supported, but we can open it back up if the need arises
