### ISSUE TITLE
DLS: Section Components - Enrollment Call To Action - Gallery Call To Action - Icons

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#229]
It seems like the icons are hiding behind the image. 

![Image](https://user-images.githubusercontent.com/7785251/170132185-ac62e8d3-7017-4315-aa4a-93b002117c91.png)

**Comment by garza-utsa** [comment]
nice catch! I didn't know these were actually here!

**Comment by garza-utsa** [comment]
https://utsa-asc.github.io/college-dls/components/detail/gallery-call-to-action.html

**Comment by garza-utsa** [comment]
+1 for outside

**Comment by Uri-E** [comment]
@lalov1 Yawp, lets keep it outside 'cause inside gonna 'cause some issues depending on the image.
