### ISSUE TITLE
DLS: Angled Buttons Large not displaying

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#258]
Seems like the buttons aren't coming up: https://utsa-asc.github.io/college-dls/components/detail/angled-button--large.html

Should they be wrapped in the `https://utsa-asc.github.io/college-dls/components/detail/angled-button--large.html` like in the demo site: https://new.utsa.edu/COLLEGE-PROTOTYPE/prototype/

**Comment by garza-utsa** [comment]
hmm, interesting, I think the only place the large buttons are used are in the enrollment cta:

https://utsa-asc.github.io/college-dls/components/detail/enrollment-call-to-action--default.html

**Comment by lalov1** [comment]
@Uri-E Fixed the issue by adding the correct classes and fixing a spelling issue.
