### ISSUE TITLE
DLS: Reconfigure Angled Button

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#261]
Could we reconfigure the Angled button, so it doesn't use font-awesome HTML inside the button? A better way of doing this might be using the after selector. If we do this, we might be able to use this button as a selectable button in the WYSIWYG. 

https://utsa-asc.github.io/college-dls/components/detail/angled-button--default.html

**Comment by Uri-E** [comment]
Okeey, I'll look into it. I was making some updates to the buttons sections on CDLS already, so I'll try 'n get at it.

**Comment by garza-utsa** [comment]
also, I just noticed, the buttons do not react the same way as the non-fa/angled buttons when on the same color backgrounds:

https://utsa-asc.github.io/college-dls/components/detail/button.html

For example, when on blue background, an orange button on hover goes to grey

<img width="535" alt="Screen Shot 2022-06-06 at 3 33 15 PM" src="https://user-images.githubusercontent.com/16828076/172243976-27cfc5b3-3413-47ba-ab74-0deccc629c6a.png">

Can we get this same behavior on all our buttons?  If we need to define more variants, let me know and I can show you how to do it =)

**Comment by lalov1** [comment]
@Uri-E Did you want me to close this issue out, or were you still working on it?

**Comment by Uri-E** [comment]
@lalov1 Fixed the color hover issue, so I think we're dun with it for now.

**Comment by lalov1** [comment]
Closing issue
