### ISSUE TITLE
DLS: Profile Info component different from reference page

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#270]
It seems like the [Profile Info](https://utsa-asc.github.io/college-dls/components/detail/profile-info.html) page differs from the [reference page](https://utsa-asc.github.io/college-dls/components/detail/faculty-profile-page.html) that shows it as an example. It seems like the image size is different, and resized differently as well. Also, the text styles are different too. It seems like the one on the reference page is a little more fleshed out.

**Comment by garza-utsa** [comment]
yeah, we need to adopt the ratio/size that we are currently using for the endowed profiles page

https://www.utsa.edu/endowed/profiles/att-inc.html

The clip path on the top corner should be css only (.clip-top-img), the contractor didn't use that class for some of the assets...

**Comment by Uri-E** [comment]
I'll hack away at it and see if I can get 'em closer to a cohesive look

**Comment by lalov1** [comment]
I think this was completed, right? Is it okay to close?

**Comment by Uri-E** [comment]
Yeah, dis dun
