### ISSUE TITLE
Alignment of Global Footer

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#274]
When you look at the global footer, there seems to be about 20px space on the left of the global footer so visually it does not look aligned to the other left elements on the page. see screenshot
<img width="143" alt="Screen Shot 2022-06-14 at 8 37 02 PM" src="https://user-images.githubusercontent.com/107521898/173717711-f54486c2-992f-47c4-a268-919b676ed681.png">

**Comment by garza-utsa** [comment]
there is definitely something odd going on with the SVG logo provided by UComm, it's getting some extra padding, the rest of the elements in the global footer are using the standard container class for all their padding, we will fix the svg spacing

**Comment by garza-utsa** [comment]
will adjust the standard container padding to 1x gutter as it is a bit small, but there is an extra layer of padding on the enrollment cta that will need to be removed to get these to match
