### ISSUE TITLE
Side Navigation

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#276]
Can we place an orange line at the top of the side navigation - it helps anchor the page esp. when it's just a headline that has the white space. It gives various flexibility for whatever is placed on the left hand side

<img width="729" alt="Screen Shot 2022-06-15 at 11 55 45 AM" src="https://user-images.githubusercontent.com/107521898/173883341-f39701c7-50ac-4611-91ff-29244325fb58.png">

**Comment by garza-utsa** [comment]
this should be an easy addition
