### ISSUE TITLE
Tab: list styling within tab component

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#277]
When you just insert an <ol> or <ul> - the font size is really large. 

It looks like for the text size to match a <p> type, you need to place an extra class="ol-list" or "ul-list" for it correct it sizing but you don't have to do it for a <p> so could the list styling be automatic vs having to always remember to add the class? 

<img width="792" alt="Screen Shot 2022-06-15 at 6 43 06 PM" src="https://user-images.githubusercontent.com/107521898/173960187-17371366-0b8a-45fc-992d-5e818b5de200.png">

**Comment by garza-utsa** [comment]
@kgarza-utsa  some of your text did not come thru, please be aware GitHub strips any html tags to prevent bad actors from embedding bad stuff
