### ISSUE TITLE
Table styles

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#278]
3 Items related to <table> styling

1) Could we default table styles without having to put `class="table-design"`? there is no default styling so that would make it easier for users.
<img width="205" alt="Screen Shot 2022-06-15 at 7 56 45 PM" src="https://user-images.githubusercontent.com/107521898/173968725-7d89549b-75a4-44db-ba98-053202c7cd52.png">

2) when you place a color class into the `<thead>` to provide an alternative color, it does not inherit that class so you have to hard-code the color - is that just a specificity issue in the CSS?
<img width="324" alt="Screen Shot 2022-06-15 at 7 57 13 PM" src="https://user-images.githubusercontent.com/107521898/173968884-07a7ab48-24fa-454a-ab96-46a968fa33f0.png">

3) because you are zebra striping your table, when you end on a white row, it looks like the last row is just floating so instead of putting a top/bottom border on the 2nd nth child, can border-bottom be placed on all the `<tr>` this way it covers the last row
<img width="310" alt="Screen Shot 2022-06-15 at 7 56 22 PM" src="https://user-images.githubusercontent.com/107521898/173968616-82643fab-6acb-4d18-abd8-9e11bd51d0da.png">

**Comment by garza-utsa** [comment]
going to assign this one to @lalov1 as he was recently tackling some other table issues in #211 

@lalov1 , @prd409-utsa, @Uri-E :  I think this is a good opportunity to add some supported color variants for table, but I'm thinking by default @kgarza-utsa is on the right track, with a plain <table >, what should the look & feel be?  For CMS editors, it would be helpful if we make the DLS table styles the default for a table w/o a class, but still have additional classes if users need to place emphasis on a specific table header row

**Comment by kgarza-utsa** [comment]
A possible option for Plain table could just be something as simple as this:

table {width:100%; margin-bottom:20px;}
th, td {border: 1px solid #0c2340; padding:12px; vertical-align:top;}

<img width="941" alt="Screen Shot 2022-06-15 at 9 30 00 PM" src="https://user-images.githubusercontent.com/107521898/173978419-0efdc30e-c2b4-4aa9-ab8f-e625dd0ba596.png">

**Comment by lalov1** [comment]
This is pending a code review, but just a heads up that if you add backticks around any HTML tag, it won't render the HTML.
