### ISSUE TITLE
Accordion Styles

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#281]
When you use the accordion for FAQ, the underlines are a bit overwhelming.

Can we:
- remove the underlines
- add a border-bottom between each element that reflect the background color.

BEFORE
<img width="1333" alt="Screen Shot 2022-06-15 at 9 14 19 PM" src="https://user-images.githubusercontent.com/107521898/173976586-ba494ddf-4583-4182-9b97-04ae29c50440.png">

AFTER
<img width="1341" alt="Screen Shot 2022-06-15 at 9 16 04 PM" src="https://user-images.githubusercontent.com/107521898/173976787-f908d4a4-a9db-45a4-a45c-f2be564bba9f.png">

**Comment by garza-utsa** [comment]
going to assign this one to @prd409-utsa as she is tackling some other issues with our accordions in #273 

@prd409-utsa feel free to discuss with the team on these proposed changes, especially with @Uri-E =)

**Comment by prd409-utsa** [comment]
The accordion title underline was removed and bottom border added in branch [accordion-expand-collapse](https://github.com/utsa-asc/college-dls/tree/accordion-expand-collapse). [It can be reviewed in this PR](https://github.com/utsa-asc/college-dls/pull/314). 

**I'm creating a new branch for <p> <li> forced sizes.**
