### ISSUE TITLE
Admissions Navigation

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#286]
Is there anway to make the admission navigation where the background has the orange angle flexible regardless of the amount of nav items placed there? This would allow for flexibility if there was ever a need to add another item on the college sites.

<img width="580" alt="Screen Shot 2022-06-15 at 10 31 29 PM" src="https://user-images.githubusercontent.com/107521898/173985091-243d7114-3f19-4e19-b68f-f3a731044237.png">

**Comment by garza-utsa** [comment]
closed via PR #291
