### ISSUE TITLE
Banner Corner Image Clip should be in CSS

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#294]
https://utsa-asc.github.io/college-dls/components/detail/banner--stripe.html
see image here how you see the corner as part of the image: https://utsa-asc.github.io/college-dls/college-dls/college/images/department-accounting.png

this is also happening to 
https://utsa-asc.github.io/college-dls/components/detail/banner--blue.html

**Comment by garza-utsa** [comment]
@Uri-E I think you had previously tackled a few padding issues like this, care to take a shot at resolving this one?

**Comment by garza-utsa** [comment]
errr, wrong issue.  This one is adding a bottom left css clip path, like our .clip-top-img class in our utility classes

https://utsa-asc.github.io/college-dls/components/detail/misc.html

**Comment by garza-utsa** [comment]
this one was fixed with the above PR #343
