### ISSUE TITLE
Alignment Issues of Stacked Call to Actions 

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#295]
When you start to stack the "Call to Actions with Image or Video" between right/left, where the text starts/ends and image starts/ends do not line up vertically. 

<img width="340" alt="Screen Shot 2022-06-16 at 1 24 57 PM" src="https://user-images.githubusercontent.com/107521898/174139908-dec7a6b2-3456-4202-9040-2d52073cfcf4.png">

**Comment by garza-utsa** [comment]
@marrv0z hey, I think this would be a good first issue to tackle, let's chat on teams on when would be a good time to go thru this and what's involved

**Comment by kgarza-utsa** [comment]
live example of the spacing issue:
https://futurenew.flywheelsites.com/programs/master/accounting/

username: utsaemcs
password: caffeinated-orca

**Comment by garza-utsa** [comment]
closed with PR #353
