### ISSUE TITLE
Responsive Issue: Banner Display

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#296]
I just happen to notice this in the DLS - not sure if someone is working on this but there seems to be an alignment issue when you reduce screen size

https://utsa-asc.github.io/college-dls/components/detail/banner--default.html

<img width="764" alt="Screen Shot 2022-06-16 at 1 34 12 PM" src="https://user-images.githubusercontent.com/107521898/174141356-74d48506-d511-4d17-a12f-ee4a37fe4396.png">

**Comment by kgarza-utsa** [comment]
So in practice, there is strange alignment issues happening in various breakpoints where it is not aligning.

<img width="907" alt="Screen Shot 2022-06-16 at 1 38 04 PM" src="https://user-images.githubusercontent.com/107521898/174141964-606feb34-1e76-464f-a901-16668dd335ad.png">

Also there might be limitations to the type of photos being used but on mobile, 

<img width="663" alt="Screen Shot 2022-06-16 at 1 38 52 PM" src="https://user-images.githubusercontent.com/107521898/174142085-bf565a70-f6a3-4705-90b5-f207b7036113.png">

there is an inconsistency between the various banners on the font size on how it works on mobile :

![IMG_5124](https://user-images.githubusercontent.com/107521898/174142484-6a5ce396-f868-4183-9a6e-56114f5cd4a1.PNG)

![IMG_5123](https://user-images.githubusercontent.com/107521898/174142491-3a407aa2-4201-46f7-800e-9e0fba985af7.PNG)

**Comment by garza-utsa** [comment]
@kgarza-utsa we can't do much with the navigation alignment as you are not using our component, but we can tackle the banner title and button alignments, looks to be missing some standard breakpoints

**Comment by garza-utsa** [comment]
alignment issues fixed with PR #298
