### ISSUE TITLE
<heading-paragraph-design> on general paragraph area

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#300]
WE modeled our general content area from the example pages and then when I try to type out simple `<h2>` and `<h3>` without an extra class, it was rendering the `<h3>` bigger and darker than the `<h2>`. Looking further, it looks like it is because we have a <heading-paragraph-design> div in that container which for some reason only has unique `<h3>` styling. 

You should probably remove that class if its not meant for general paragraph areas? 

<img width="600" alt="Screen Shot 2022-06-16 at 9 07 56 PM" src="https://user-images.githubusercontent.com/107521898/174208913-7fcb4093-d9c7-4d45-81f6-d5b33717efbc.png">

<img width="678" alt="Screen Shot 2022-06-16 at 9 11 07 PM" src="https://user-images.githubusercontent.com/107521898/174210015-8275b270-9779-4114-9e6d-c884980d58e6.png">

**Comment by garza-utsa** [comment]
yeah, this div/class shouldn't be here.  any page content styling should be attached to the .page-text-wrapper
