### ISSUE TITLE
Accordion - forced <p> styles ?

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#301]
I noticed that there is a defined class under accordion for a paragraph that differs the font size from the normal `<p>` style. Is that necessary? There is also rather large margin styles too. Maybe there only needs to be a margin-top instead of both top and bottom?

<img width="201" alt="Screen Shot 2022-06-16 at 9 46 42 PM" src="https://user-images.githubusercontent.com/107521898/174214810-2c1c75c2-89ef-46be-980c-7ed0c1cfc027.png">

In this image, you can see how the accordion `<p>` style differs from the `<li>` style. and there is also a forced `font-size` typed out in an `<li>` style under accordion.

<img width="231" alt="Screen Shot 2022-06-16 at 9 48 43 PM" src="https://user-images.githubusercontent.com/107521898/174214994-9133bd00-8058-421c-913c-d2363b2277c9.png">

<img width="343" alt="Screen Shot 2022-06-16 at 9 48 02 PM" src="https://user-images.githubusercontent.com/107521898/174214933-ca03e170-2ff0-42b7-8fad-e831fbb427a2.png">

**Comment by garza-utsa** [comment]
can definitely remove, don't think these are here for any good reason

**Comment by garza-utsa** [comment]
@prd409-utsa, please do remove this as part of #281
