### ISSUE TITLE
Banner: New Variant Orange

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#302]
Can we please have a new variant for an orange version of this banner? I'd like to use those for our call to action instructional pages like "apply" and "check status" vs our informational pages where we will use blue.

https://utsa-asc.github.io/college-dls/components/detail/banner--blue.html

**Comment by garza-utsa** [comment]
👍

**Comment by lalov1** [comment]
Might be another good one for @marrv0z
