### ISSUE TITLE
New Componenet 

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#306]
Just thinking about building out degree program pages ... I saw this on the ACOB program page and thought about the situation when a program has a lot of faculty they want to highlight but that could make the page very long to scroll through - esp. since the program page will have a lot of content, so putting profiles in a carsoel feature would be nice. 

<img width="1048" alt="Screen Shot 2022-06-17 at 1 51 05 PM" src="https://user-images.githubusercontent.com/107521898/174379961-1cb5f67d-62f7-4024-895c-44ecc8b6a6b7.png">
https://business.utsa.edu/executive-programs/cpe-emba/

**Comment by garza-utsa** [comment]
will not implement, carousels bad!

research shows, content behind a carousel (i.e.- anything not on the first slide) is never seen by users.  Plus you need to safely implement play/pause functionality and keyboard-only operation.  We made an exception for the banner, but we will be heavily discourage that usage as well.

that being said, I would instead use the already implemented [faculty-group](https://utsa-asc.github.io/college-dls/components/detail/faculty-group.html) component which features 3-up like this and has a call to action link which can be utilized to go to a full faculty listing page
