### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#313]
If you happen to have buttons across multiple columns within a row, and they stack on mobile, there is no spacing between the buttons. Perhaps a `.mb-1` could be added either to the `-action-btn` class or when it its a certain breakpoint. 

<img width="1059" alt="Screen Shot 2022-06-20 at 9 45 12 PM" src="https://user-images.githubusercontent.com/107521898/174705391-b19ee4ce-8e57-4834-9a2a-79cd36cbc5a9.png">

<img width="447" alt="Screen Shot 2022-06-20 at 9 45 01 PM" src="https://user-images.githubusercontent.com/107521898/174705367-02d64446-7b32-4127-8a07-33e507224184.png">

with `.mb-1` added

<img width="1046" alt="Screen Shot 2022-06-20 at 9 48 15 PM" src="https://user-images.githubusercontent.com/107521898/174705746-850b761d-f0a6-4142-ae81-72b2fc56236d.png">

<img width="469" alt="Screen Shot 2022-06-20 at 9 47 59 PM" src="https://user-images.githubusercontent.com/107521898/174705715-e5a20acd-4ea0-4852-b614-a0e5761da249.png">

**Comment by garza-utsa** [comment]
@marrv0z let us know if you need help with this one =)

**Comment by lalov1** [comment]
Could this be closed? I think this PR addressed this, right? https://github.com/utsa-asc/college-dls/pull/415

**Comment by garza-utsa** [comment]
oh hmm, that is correct, this was fixed in #415
