### ISSUE TITLE
Color Classes

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#323]
I'm experiencing that when I apply a color class to a header tag, its not taking that color. Not sure if its due to a specifcility in the styles.

example the code is `<h4 class="pt-2 blue">Distinguished Scholarship</h4>` but it still displays the `h4` as orange

<img width="425" alt="Screen Shot 2022-06-21 at 7 56 37 PM" src="https://user-images.githubusercontent.com/107521898/174920756-04f26564-a02d-481b-8f80-5a19b8ad6196.png">

**Comment by garza-utsa** [comment]
@kgarza-utsa yes, the headings are scoped for this component as orange, if @Uri-E is ok with this, we can remove this styling and let users set their styles as described above, we would probably want this for accordions too?

**Comment by Uri-E** [comment]
Yeah, I think we can remove it and let the headers default to the global setting. Then users can customize it if they want.
