### ISSUE TITLE
Accordion Padding

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#333]
Hello, it's me again. 

With more extensive uses of the accordion, it appears that too much internal padding was taken away (or maybe it wasn't there to begin with? getting it confused with tabs). 

I'd like to recommend we double from 1.5rem to 3rem for `.accordion .card-body` across the board. it would actually mirror the current spacing for tabs (although the reference padding is different). I would even say for desktop view you can increase it a little more to 4rem and have the mobile default be 3rem. 

ALSO - I'm realizing there really isn't good default `<li>` styles ... is it just me or does the spacing between list items look tight? When I looked in the DLS, there is only "enhanced" list styles where you have to add classes. Perhaps even a padding-bottom of `3px` or `4px` would give some nice visual spacing, then on `li:last-child` remove the padding bottom

ALSO - did you know there is no default `<p>` styles either? they all have to have a class .`paragraph-text` attached to it. should we eliminate that class or adopt that class as the default `<p>`?

**current accordion padding**

<img width="600" alt="Screen Shot 2022-06-22 at 9 38 18 PM" src="https://user-images.githubusercontent.com/107521898/175195318-edf9b01e-9e29-4a41-908e-55d9607fbe61.png">

**proposed accordion padding**

<img width="600" alt="Screen Shot 2022-06-22 at 9 38 05 PM" src="https://user-images.githubusercontent.com/107521898/175195279-1eb455bc-f295-4ba1-8f1c-40a126fe1567.png">

<img width="600" alt="Screen Shot 2022-06-22 at 9 40 49 PM" src="https://user-images.githubusercontent.com/107521898/175195606-436422c5-811b-43d4-b51e-e487bf074467.png">

**Comment by garza-utsa** [comment]
@kgarza-utsa this sounds like three different issues, can you create a separate issue for default stylings with `<p> and <li>`?

**Comment by garza-utsa** [comment]
however, I do agree, the intent was to make the padding consistent between accordion and tabs, will need to fix this
