### ISSUE TITLE
max-height needed on banner components?

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#336]
on sizes past lg, the banner gets to be way too long?
![Screen Shot 2022-06-22 at 10 15 34 PM](https://user-images.githubusercontent.com/16828076/175199875-ead0e68b-f53d-4f40-821f-5d889f82168b.jpg)

maybe enforce a max height with some nice background-cover properties, except the images aren't background-urls...

**Comment by lalov1** [comment]
What about adjusting the breakpoints for `xxl` to `xxl-8` and `xxl-4`?
