### ISSUE TITLE
Typography - Headline Colors

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#347]
Hello - I thought we were going to remove color styles from the heading classes so that users can declare the color needed?

Unfortunately when I add the class `.orange` onto a `.h6` the blue on the `.h6` takes precedence and ignores the `.orange` class.

Can the `color: $blue;` be removed? or do we need to just hard-code in-line color styles?

<img width="275" alt="Screen Shot 2022-06-27 at 7 20 04 PM" src="https://user-images.githubusercontent.com/107521898/176060831-1552667a-bce6-4f1d-a3f6-852e0a87fd0b.png">

**Comment by lalov1** [comment]
Maybe we could do helper classes like Bootstrap does with `text-white` to help fix this issue. 

https://getbootstrap.com/docs/4.5/utilities/colors/

**Comment by kgarza-utsa** [comment]
Aren't the color classes `.orange`, `.blue` like helper classes already? https://utsa-asc.github.io/college-dls/components/detail/color.html

 It might be a hierarchy issue too where these color classes are getting called too early so any color styling to classes further on the stylesheet over-writes those?

**Comment by Uri-E** [comment]
@kgarza-utsa Ahh, OK, I think I see what's up. All the headers should be added as <h> tags, not classes. So to get the orange color, add it like so:

<h6 class="orange">How to Submit a Fee Waiver</h6>

Some of the H tags have a class="h4" or class="h3", etc. That's only to adjust the sizing, but still keep the correct hierarchy for accessibility purposes (H1 followed by H2 followed by H3, etc.).

**Comment by kgarza-utsa** [comment]
@Uri-E so the issue we have is that we are using the `<h1>` `<h2>``<h3>``<h4>` etc. to maintain content hierarchy but we don't always like the sizing of those headings depending on the pages so we do use the `.h2` `.h3` `.h4` to manipulate the sizing. Perhaps we need sizing classes instead then so we can manipulate size and color via class? 

example of how we used those classes

`<h3 class="h4">Pay Application Fee</h3>`
`<p class="h6 pt-2 orange">Pay Fee Online</p>`

thoughts?

**Comment by garza-utsa** [comment]
closed with Uriel's PR #354
