### ISSUE TITLE
Accordion Color Thoughts

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#348]
After using the accordion for quite a few items, I wonder if going dark blue background is a bit too stark. 

Example executions: 
Instructions - https://futurenew.flywheelsites.com/freshman/admissions/
FAQ - https://futurenew.flywheelsites.com/freshman/admissions/srar/

I'd like to prpose flipping the color so that it starts off with light background `#f6f6f6` then use dark for the active setting. This color pairing is much easier on the eye when you pair the accordion next to other components, especially the tab. What's nice too is that when the accordion expands, it carries the same orange border at the top that you see the in tab. The (+) can also be orange too, just to give it an extra dimension so its just not blue text on light gray.

PS: I also noticed there is a background-image URL attached to `.accordion-button:after` that is hidden because its the same background color as the blue but it looks unnecessary so it can probably be removed. 

---------------------------------

`proposed default being the light gray #f6f6f6`

> <img width="80%" alt="Screen Shot 2022-06-27 at 9 45 46 PM" src="https://user-images.githubusercontent.com/107521898/176080791-54b57bf4-da53-41e7-b92b-b4a519c59d95.png">

`vs below which is what currently exists`

> <img width="80%" alt="Screen Shot 2022-06-27 at 9 47 52 PM" src="https://user-images.githubusercontent.com/107521898/176081050-278eb556-188c-4627-94a8-58f63da70a0a.png">

---------------------------------

`proposed on expand, it becomes dark blue`

> <img width="80%" alt="Screen Shot 2022-06-27 at 9 50 23 PM" src="https://user-images.githubusercontent.com/107521898/176081345-ef6ad786-6ed7-4e02-be83-28d4b3afbcd7.png">

`vs below which is what currently exists`

> <img width="80%" alt="Screen Shot 2022-06-27 at 9 48 33 PM" src="https://user-images.githubusercontent.com/107521898/176081135-385328bd-1274-4383-92d6-1602cf5f9e9a.png">

**Comment by prd409-utsa** [comment]
@garza I get what you are saying, but to me in the new color scheme the accordions that follow (5,6 in your screenshot) get lost or blend in as part of the content of the expanded accordion.  
Your original screenshot of new color scheme 
<img width="848" alt="Screen Shot 2022-06-28 at 9 23 52 AM" src="https://user-images.githubusercontent.com/92815346/176205765-f4a0c175-f48e-46c0-a480-d128ce3c0053.png">


Maybe add a bottom border to the expanded state? Orange to match the top border maybe? Or I actually like the UYSA blue for it. See my screenshots. 

@Uri-E  @lalov1 your opinions would be great on this also.

Orange bottom border on expanded accordion
<img width="857" alt="Screen Shot 2022-06-28 at 9 27 17 AM" src="https://user-images.githubusercontent.com/92815346/176205586-57813207-b7ed-440c-98a3-47003ae7bcb7.png">



Blue bottom borer on expanded accordion
<img width="878" alt="Screen Shot 2022-06-28 at 9 27 35 AM" src="https://user-images.githubusercontent.com/92815346/176205639-1343f237-f68a-419f-952e-aed38d2d38e8.png">

**Comment by lalov1** [comment]
I think adding the border would work and the new solution looks better!

**Comment by prd409-utsa** [comment]
@kgarza-utsa also your two example links require a password, so I wasn't able to view them.

Example executions:
Instructions - [](https://futurenew.flywheelsites.com/freshman/admissions/)
FAQ - [](https://futurenew.flywheelsites.com/freshman/admissions/srar/)

**Comment by kgarza-utsa** [comment]
The blue line at the bottom below is nice. 

@prd409-utsa 
user: utsaemcs
pw: caffeinated-orca
