### ISSUE TITLE
DLS: Global Footer Line Height and Width

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#350]
Do you think we should reduce the `line-height` for the links in the footer? For a second, I thought "Roadrunner Remembrance" was two separate items: https://utsa-asc.github.io/college-dls/components/detail/global-footer.html

Also, for some of the items that wrap, they are at 100% width. Do you think we should adjust them all, so they are 100% width? 

Proposed changes:
````
#footer .nav-item>a {
    line-height: 20px;
    width: 100%;
    margin-bottom: 5px
}
````

**Comment by Uri-E** [comment]
I think that's a good point. The default on body text is line-height: 1.5; which I think would work fine.

**Comment by garza-utsa** [comment]
think I made a boo boo when copying the html from utsa.edu, that last column should be col-lg-4 not col-lg-2.  But either way, we should adopt the same line-height as https://www.utsa.edu
