### ISSUE TITLE
CMS: Faculty-Group Filtered

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#363]
Take the existing Faculty-Group component and create a new secondary component "Faculty Group - Filtered" that uses any assigned tags to present all faculty that share those same tags (hasAny).

https://walledev.it.utsa.edu/entity/open.act?id=01ced2af81736a1b3244dcc1b4193a1f&type=block

**Comment by garza-utsa** [comment]
Example of some query api with hasAny tag calls:

https://walledev.it.utsa.edu/entity/open.act?id=e54d56b8817364bb54647658d87cdc25&type=format

This code is definitely not as clean as our college code, beware!

**Comment by lalov1** [comment]
Hi @garza-utsa - Let me know if this is what you had in mind:
https://walledev.it.utsa.edu/entity/open.act?id=d1f632af81736a1b3be11e0671f220d2&type=page

Once the user adds a tag on the page and selects the "Faculty Group Filtered" row it's filtered. 
https://walledev.it.utsa.edu/entity/open.act?id=de29c20e81736a1b3773764cd5d2137c&type=format

I'm only grabbing the first tag right now, but I could grab all tags if you would like. 

Also, I have a couple of warning messages if the user doesn't add a tag or adds more than one. 

Let me know your thoughts.

**Comment by garza-utsa** [comment]
I think we want to encapsulate this into a block just like faculty-group, I'm thinking on the case where we might want to have multiple faculty-block-filtered on a page, each with their own filters.

For the block itself, I think we want to support multiple tags, just got to think thru, expectation-wise, if the faculty-group block has two tags assigned, are we expected to return any faculty with either of those tags (hasAny) or return only faculty that have both of those tags (hasAll)

**Comment by lalov1** [comment]
@garza-utsa This is completed, but we could always refactor it later: 
https://walledev.it.utsa.edu/entity/open.act?id=d1f632af81736a1b3be11e0671f220d2&type=page
