### ISSUE TITLE
CMS: Faculty Block revisions

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#364]
title and title 2 need to be consolidated into a repeatable field with a minimum of 1 and a maximum of at least 3 (I'm thinking maybe 4 or 5?).

We've already identified some faculty who hold more than 2 titles:
- Appointment (Associate Professor)
  - some faculty have multiple appointments in different departments!
- AVP title
- Department chair
- Endowed title
- Dean title

So that's potentially 6 different titles for a single faculty member (worst case), so may no maximum...

**Comment by lalov1** [comment]
Hi @garza-utsa - I think I got this working:
https://walledev.it.utsa.edu/entity/open.act?id=d1f632af81736a1b3be11e0671f220d2&type=page

I added the five titles to your faculty block. 

Here is the velocity file: 
https://walledev.it.utsa.edu/entity/open.act?id=b603612981736a1b3773764ccdd5ba91&type=format
