### ISSUE TITLE
Still having issues with color class

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#367]
@lalov1 @Uri-E

I'm still having issues where adding the color class like `.orange` is not changing the heading to orange

<img width="522" alt="Screen Shot 2022-07-08 at 11 39 43 AM" src="https://user-images.githubusercontent.com/107521898/178034396-134da16f-728f-4c0b-b7be-974f4df9c2dd.png">

<img width="863" alt="Screen Shot 2022-07-08 at 11 40 35 AM" src="https://user-images.githubusercontent.com/107521898/178034528-70a4abac-4f48-49d6-a082-9ddc673c33a5.png">

https://futurenew.flywheelsites.com/freshman/admissions/

**Comment by kgarza-utsa** [comment]
should the color classes be listed towards the end of the stylesheet for specificity order so it does take?

**Comment by Uri-E** [comment]
Hmm, it looks like the CSS is being compiled the same way as it was before, with headers h1, .h1 { ... } and so on together instead of on separate lines. It should be...

```
h1 {
	font-size: 3rem;
	color: $blue;
	font-weight: 700;
}

.h1 {
	font-size: 3rem;
	font-weight: 700;
}
```
...and so on, so the classes don't have a color property added to them. Unless the CSS hasn't been updated on these sites yet? @garza

**Comment by kgarza-utsa** [comment]
any thoughts on this item? @Uri-E @garza

**Comment by garza-utsa** [comment]
let me do some testing or scss order/precedence, I think we can solve this with how we've setup when each section in our visual-styling section gets parsed...

**Comment by garza-utsa** [comment]
@kgarza-utsa can you share a public URL with this issue?

**Comment by kgarza-utsa** [comment]
like this one @garza-utsa https://futurenew.flywheelsites.com/freshman/admissions/ ?
