### ISSUE TITLE
DLS: Faculty listing with no link isn't displaying correctly

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#374]
I was trying to make it a little more dynamic, but when you hide the link the class is associated with it. 
![Image](https://user-images.githubusercontent.com/7785251/178550245-17d16ef9-ab64-41d5-b2d0-a7d9ab945521.png)

**Comment by garza-utsa** [comment]
https://utsa-asc.github.io/college-dls/components/detail/profile-card--default.html

Hmm, what should we do when the markup doesn't have an anchor tag, but the DLS does?

**Comment by lalov1** [comment]
Maybe do another variant without the link?
