### ISSUE TITLE
Table Mobile View

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#379]
it looks like there is padding that doesn't quite favor complex tables.

current: `.table-design tr td, .table-design tr th {padding:10px 15px;}`

could we reduce the right/left padding a little bit, maybe just to 10px overall?
proposed: `.table-design tr td, .table-design tr th {padding:10px;}`

<img width="323" alt="Screen Shot 2022-07-12 at 9 18 29 PM" src="https://user-images.githubusercontent.com/107521898/178636853-410b0eab-6c39-4686-ab3d-76d997d28775.png">

<img width="329" alt="Screen Shot 2022-07-12 at 9 20 09 PM" src="https://user-images.githubusercontent.com/107521898/178637005-99ed6f09-2aff-40b2-a17a-14cee7a4f98b.png">

**Comment by kgarza-utsa** [comment]
thanks @lalov1 , hmm, what is the purpose of wrapping the table in an outer div that couldn't be established with the table class? I wonder if that is not a necessary item and not intuitive for someone to remember when they insert a table on a page.

**Comment by lalov1** [comment]
Yep, it's something a little more technical for users to remember, but it does help with the horizontal scrolling on mobile: 
https://getbootstrap.com/docs/4.5/content/tables/#responsive-tables

My only concern with your solution is a larger table than your example will be the same problem. Also, it might be a little smooshed, depending on the size.

**Comment by lalov1** [comment]
For some reason, the vendor created a new class that does the same as the bootstrap classes. 😄 Feel free to use the bootstrap classes. I will close the issue, but let me know if you have issues with the responsive tables. 

Tables are notorious for being hard to work with on mobile.
