### ISSUE TITLE
fyi - Navigation iOS alignment 

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#381]
FYI while we were fixing some alignment issues with our custom version of the navigation for admissions, our developer noted this:

"I fixed the iOS alignment issue, BUT I do see that the DLS has issues with alignment for devices **smaller than** iphone 8 plus. Confirmed it happens when testing it directly from DLS component website."

**Comment by garza-utsa** [comment]
Looks like sizes under 378 is when this starts to behave badly:

<img width="444" alt="Screenshot 2022-07-13 at 4 13 53 PM" src="https://user-images.githubusercontent.com/16828076/178837265-7b1083f7-d746-4f44-90c0-2657edfa985b.png">
