### ISSUE TITLE
Content List Modificatons

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#391]
https://utsa-asc.github.io/college-dls/components/detail/content-list--default.html

1. Can we use the same border-line size on `.highlight-card` to match the border-line that we use on our accordion tab for consistency? So change from 12px to 6px
2. Can we increase the font size for `.highlight-card-link` pretty please from 1.3rem to 1.6rem

**Comment by garza-utsa** [comment]
@kgarza-utsa getting pretty into the weeds, eh?
