### ISSUE TITLE
Orange Line on Card Components + Issue with button on Card Component 

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#398]
Could we have the orange border be on the bottom of the image so that it always sandwiches between the image and the content? If the event card ever had an image on top, that orange line would also work as is for a nice separation. This is the style we worked with on the alternative profile card for staff as well that I submitted in #394 

also, the same border thickness should be applied to the event card (the 6px) so that orange rule can remain consistent.

https://utsa-asc.github.io/college-dls/components/detail/content-card--default.html
https://utsa-asc.github.io/college-dls/components/detail/event-card--default.html

Also - we decided to go with the regular blue-btn instead of an action btn on the content card but there seems to be a conflict with the button class with the content card card
<img width="280" alt="Screen Shot 2022-07-19 at 5 53 03 PM" src="https://user-images.githubusercontent.com/107521898/179861639-b433935e-d2b7-46b6-8c44-8501ef1d3f84.png">

<img width="1054" alt="Screen Shot 2022-07-19 at 5 51 33 PM" src="https://user-images.githubusercontent.com/107521898/179861483-7799de0d-d671-4751-9552-a5db18a3b232.png">

cc @Uri-E @garza

**Comment by garza-utsa** [comment]
I'm going to split out the regular button in this component issue to another issue

**Comment by kgarza-utsa** [comment]
Thoughts --- I think it will look nice to have the orange border separating from content to the image. I just mocked them up to see and I think they look good ... minus the idea for the tab. thoughts?

**Tab** 
personally, I still prefer the line on top than bottom for tab.

<img width="150" alt="Screen Shot 2022-07-20 at 11 33 56 AM" src="https://user-images.githubusercontent.com/107521898/180035684-dde32a7a-f855-4973-a499-dff909d9bfdf.png"><img width="150" alt="Screen Shot 2022-07-20 at 11 34 47 AM" src="https://user-images.githubusercontent.com/107521898/180035816-8c2bd171-3b33-447c-a687-2a379163c683.png">

**Accordion** 
I think moving the orange line down would be okay for accordion.

<img width="300" alt="Screen Shot 2022-07-20 at 11 37 12 AM" src="https://user-images.githubusercontent.com/107521898/180036237-bf404ebd-6a20-420b-9aa6-0abef97c01da.png">

**Content Card**

<img width="300" alt="Screen Shot 2022-07-20 at 11 23 52 AM" src="https://user-images.githubusercontent.com/107521898/180033721-12508d66-84f1-4c3c-a85d-47f3b7b0456a.png">

**Action Card**

<img width="300" alt="Screen Shot 2022-07-20 at 11 25 01 AM" src="https://user-images.githubusercontent.com/107521898/180033931-d769cf10-0799-4b65-b0df-548917c25c58.png">

**Event Card**

<img width="300" alt="Screen Shot 2022-07-20 at 11 25 57 AM" src="https://user-images.githubusercontent.com/107521898/180034087-f4214060-79f8-4113-8ad5-71a0339aeb42.png">

**News Card**

<img width="300" alt="Screen Shot 2022-07-20 at 11 22 56 AM" src="https://user-images.githubusercontent.com/107521898/180033559-c86754e1-8a9d-4415-9133-361c118048e1.png">

**News Card**

<img width="300" alt="Screen Shot 2022-07-20 at 11 22 56 AM" src="https://user-images.githubusercontent.com/107521898/180033559-c86754e1-8a9d-4415-9133-361c118048e1.png">

**Profile Card**

<img width="300" alt="Screen Shot 2022-07-20 at 11 32 36 AM" src="https://user-images.githubusercontent.com/107521898/180035381-15b8fbb5-e171-4596-83ff-37faa1a260b2.png">
