### ISSUE TITLE
Sidebar - Side Navigation Issue

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#400]
Hello. We noticed when you start your side navigation with a grouped item, when you expand it, it kicks in that first list item border top. Is there a way to null that if it's a grouped sub menu that is the first item? 

<img width="349" alt="Screen Shot 2022-07-20 at 9 26 03 AM" src="https://user-images.githubusercontent.com/107521898/180007100-77fcf381-11d4-4a5e-a6c6-7f17824ab3a0.png">

**Comment by garza-utsa** [comment]
Are y'all sticking to the DLS html?

<img width="419" alt="Screenshot 2022-07-20 at 10 00 03 AM" src="https://user-images.githubusercontent.com/16828076/180015266-b3afcaf3-3dd3-43c9-9ca9-17d90255df6a.png">
<img width="1035" alt="Screenshot 2022-07-20 at 10 01 21 AM" src="https://user-images.githubusercontent.com/16828076/180015530-7fd99161-06c0-4166-a0d0-0be77aad9401.png">

**Comment by kgarza-utsa** [comment]
Yes, but the first item is the expanded item ... so it seems like it is creating that that top line with the first li item I think? @garza-utsa

**Comment by garza-utsa** [comment]
forgot to revert the first child of first item issue

**Comment by garza-utsa** [comment]
fixed in #399
