### ISSUE TITLE
regular button color issue inside card components

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#402]
Anchor classes are conflicting with regular button coloring inside some of our components

![](https://user-images.githubusercontent.com/107521898/179861483-7799de0d-d671-4751-9552-a5db18a3b232.png)

**Comment by kgarza-utsa** [comment]
@garza-utsa do you think this will get committed today to close out?

**Comment by garza-utsa** [comment]
@kgarza-utsa just awaiting code review =)
