### ISSUE TITLE
disappearing slim banner? 

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#405]
hello, we noticed all our pages that use the slim banner no longer is rendering and noticed it is not rendering on the DLS site

https://utsa-asc.github.io/college-dls/components/detail/banner--slim.html

Would someone be able to look into this and reinstate the style? 

cc @lalov1 @garza

**Comment by lalov1** [comment]
@garza-utsa Looks like the `.single-title-wrapper` class got deleted? 
````
.single-title-wrapper {
    background-color: #0c2340!important;
    padding: 95px 15px;
}
````
<img width="801" alt="Screen Shot 2022-07-21 at 10 39 30 AM" src="https://user-images.githubusercontent.com/7785251/180255207-27f4cd63-739f-484c-bfc5-161bfdbb689d.png">

**Comment by garza-utsa** [comment]
whoops, was a bit ambitious in removal of _vendor.scss stuff, will revert this deletion
