### ISSUE TITLE
white line between card-img and card-content

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#408]
I'm not seeing this 100%, but since we moved the top-border to the card-content elements, I'm seeing a white line now above the orange border, here is one on the programs listing page:

https://utsa-asc.github.io/college-dls/components/preview/program-listing-page.html

<img width="518" alt="Screenshot 2022-07-22 at 3 53 25 PM" src="https://user-images.githubusercontent.com/16828076/180567195-b1f9472f-d721-48ed-bf15-7dac464810c5.png">

**Comment by Uri-E** [comment]
That's weird, I don't see it anywhere... maybe it's browser specific?

Or some kind of ghost.

**Comment by garza-utsa** [comment]
hmm, another safari only bug...can't reproduce on other browsers
