### ISSUE TITLE
DLS: Skip to Content Links

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#419]
https://css-tricks.com/how-to-create-a-skip-to-content-link/

**Comment by garza-utsa** [comment]
Looks like our template already has a div defined for this, maybe just needs better markup/styling.  I think this was one of the classes that was defined with various mis-spellings and typos...

<img width="547" alt="Screenshot 2022-07-29 at 2 55 27 PM" src="https://user-images.githubusercontent.com/16828076/181834255-db5d4cc1-9aaa-4b6a-8478-bfac266601e9.png">

**Comment by lalov1** [comment]
It looks like it's there, but when you hit enter, it only scrolls down 200px from the top:
````
    $(".Skip-btn").click(function () {
        $("html").scrollTop(200);
    });
````

A better functionality might be to have it focus on a specific section since when you start to tab again, it shoots back up. 

Also, it might be nice to have other areas added as well. For example, at UIW, we had functionality to take them to the top navigation.

**Comment by garza-utsa** [comment]
agreed, all the skip-btn logic should be in script.js (src/js/script.js)
