### ISSUE TITLE
A11Y: keyboard navigation (focus state)

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#421]
after a successful page load, I cannot see my focus state as I press tab on my keyboard

**Comment by lalov1** [comment]
This seems to work for me in Chrome, but it's working a little weird in Firefox. Is this in Safari for you?

**Comment by lalov1** [comment]
@garza-utsa It looks like you have to enable this for Safari and Firefox:
- https://corehelpcenter.bqe.com/hc/en-us/articles/115003481673-Tab-key-is-not-working-on-Mac-Safari
- https://support.mozilla.org/en-US/questions/1278793

I do see some focus issues with accordions, so I'll give that a look.
