### ISSUE TITLE
A11Y: banner background color fallback needed when no image loads

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#428]
some more defensive css styling might be needed on our banner classes, when an image doesn't load, we end up with a white H1 on white background
<img width="1752" alt="Screenshot 2022-08-02 at 9 57 28 AM" src="https://user-images.githubusercontent.com/16828076/182406302-cd545911-82b3-4b95-bf75-c5a3b82c4546.png">
.

**Comment by lalov1** [comment]
This seems to be fixed: 
![Image](https://user-images.githubusercontent.com/7785251/196474508-46f4d6d7-29eb-46d9-956b-7d0288db02d9.png)

Is it okay to close?

**Comment by garza-utsa** [comment]
sounds good, closing now =)
