### ISSUE TITLE
DLS: Top Navigation Callout Overlap

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#429]
When you click on an item that overlaps with the div where the CTA is in the top navigation, you can't click on it. This seems to be because of the z-index for that item. One solution could be for the top navigation to hide when scrolling down and return if the user scrolls up. We did this with one of our websites at UIW: 
https://my.uiw.edu/current-students/

![Image](https://user-images.githubusercontent.com/7785251/182404743-46afeb45-241a-4d77-ad5c-cbee93f0f7da.png)

**Comment by garza-utsa** [comment]
let's do it!
