### ISSUE TITLE
Accordion overflowing when an image is added

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#430]
This happens when I add an image higher than the content. I thought it was working previously. 

![Image](https://user-images.githubusercontent.com/7785251/182430393-5376077c-52b0-4c28-8489-42a7cf371f3e.png)

**Comment by prd409-utsa** [comment]
Still unsure about this one. I had done some research but everything I've found says that an image needs to be in a div when in a flexbox container.

**Comment by lalov1** [comment]
@prd409-utsa It looks like if you add a `display: inline-block` to the `.accordion .accordion-body-content` selector it works correctly. What do you think?

**Comment by prd409-utsa** [comment]
I'll cut a branch and look into it. Thanks for the tip, @lalov1

**Comment by prd409-utsa** [comment]
Code here () :""

**Comment by prd409-utsa** [comment]
That worked and just submitted PR.  I was thinking that the solution wanted was something like making variants:

1. image on left next to content
2. image on right next to content

That's what got me so bogged down in trying to figure out how all that would work, especially in the CMS data definition and format!

**Comment by prd409-utsa** [comment]
But I am understanding the velocity formats much better now so maybe I will try and implement something like that... down the road!
