### ISSUE TITLE
DLS: Full width content callout (no image, no cta)

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#431]
With Uriel's [excellent mockups](https://xd.adobe.com/view/f483b230-cacb-4b61-bb40-29dad0f15808-a1d0/specs/), we got 3 variants to code up in the DLS.

Since this is a full width type of component, suggested new home:
- components/03-sections/08-content-callout

Three variants needed: default (white bg), blue, orange.

**Comment by garza-utsa** [comment]
Cascade implementation notes:
- Data Definition:
- Headline
- Subheading (optional)
- Text (WYSIWYG or Text Area?)
- Format
- Base Asset and Factory

**Comment by prd409-utsa** [comment]
First stab at this. 
<img width="1346" alt="Screen Shot 2022-08-03 at 5 46 10 PM" src="https://user-images.githubusercontent.com/92815346/182725547-396798e1-1d79-4b5e-a0d5-c8cc806410c9.png">
<img width="1581" alt="Screen Shot 2022-08-03 at 5 46 27 PM" src="https://user-images.githubusercontent.com/92815346/182725553-4c61cbed-2121-4dfc-b54e-4ebd9d5f925a.png">
<img width="1587" alt="Screen Shot 2022-08-03 at 5 46 41 PM" src="https://user-images.githubusercontent.com/92815346/182725554-0dead8ba-0ef3-4fcd-b815-0a3680f18cf3.png">
