### ISSUE TITLE
CMS: Right nav links with secondary page links

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#454]
If you click on a link with secondary page links and don't click on the plus icon it shoots you up to the top of the page. Should it link to the index page instead? 
https://ceidtest.utsa.edu/student/about.html

![Image](https://user-images.githubusercontent.com/7785251/188745130-429af3fb-ea6a-4412-bf52-c6faee01aa87.png)

**Comment by prd409-utsa** [comment]
I've noticed this too. And yes, I think it should go to the index page for that section. I'll take a look at it.

**Comment by lalov1** [comment]
I spoke to @garza on this one yesterday and he stated since we don't have a way to link "Programs" it should have the same functionality as the plus/minus icon.

**Comment by garza-utsa** [comment]
yeah, should be the same behavior as the top nav, the data definitions do not allow us to set a URL for dropdown labels
