### ISSUE TITLE
CMS: CTA and other components not able to accept an email

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#456]
We need to update the `linkData` macro to make sure it could accept an email as a value. We might be able to check to see if the value contains "@utsa.edu" and then make sure it has the `mailto:` link info. 

![Image](https://user-images.githubusercontent.com/7785251/188894496-9453ac0e-76d2-4766-96bd-695254e182c7.png)

**Comment by prd409-utsa** [comment]
I think creating an external-link file, the way John David suggested, solves this issue without having to do anything to the component itself.

**Comment by lalov1** [comment]
I tested the mailto: and it works on the component as well: https://walledev.it.utsa.edu/entity/open.act?id=d1f62e2381736a1b3be11e06dbd62aa3&type=page

I'll close the issue.
