### ISSUE TITLE
CMS: Skipped heading levels for footer headings

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#472]
Maybe change the headers to the h5 class instead of using h5's:

![Image](https://user-images.githubusercontent.com/7785251/190265310-e93ca92d-d9ce-4c72-bbbd-ed62a3caac6c.png)

**Comment by garza-utsa** [comment]
removed the social section as that does not exist for Klesse and updated the remaining H5s to H2s with .h5
