### ISSUE TITLE
CMS: Create News Group Filtered component

### ISSUE THREAD

**Issue by prd409-utsa** [utsa-asc/college-dls#480]
Need the ability to filter news articles by tags (like how faculty filtered tags work)

**Component:** newsGroupFiltered 
**format:**  [https://walledev.it.utsa.edu/entity/open.act?id=61438f1281736a1b003cf7c3b898c12b&type=format](https://walledev.it.utsa.edu/entity/open.act?id=61438f1281736a1b003cf7c3b898c12b&type=format)
(This is a copy of facultyGroupFiltered component format as a base)

**Data Definition:** News Filtered 
**data-definition:** [https://walledev.it.utsa.edu/entity/open.act?id=6156fae481736a1b003cf7c390d15897&type=structureddatadefinition](https://walledev.it.utsa.edu/entity/open.act?id=6156fae481736a1b003cf7c390d15897&type=structureddatadefinition)
(This is a copy of Faculty Filtered data def as a base)

**Comment by garza-utsa** [comment]
programGroupFiltered will be another good resource, make sure and test on WALLEDEV first, please =)

**Comment by garza-utsa** [comment]
Extra credit:

- Add dropdown to data definition to support display 3 or 6 items

**Comment by lalov1** [comment]
I think this is completed, right?

**Comment by garza-utsa** [comment]
yup, going to go ahead and close, this is working and exported into cascade
