### ISSUE TITLE
DLS: Interactive Controls must not be nested

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#489]
WCAG 2.1 Level A: https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

![Image](https://user-images.githubusercontent.com/7785251/192555872-55a4628b-4fcd-4497-a211-3e5d4591fb21.png)

**Comment by garza-utsa** [comment]
oh hmm, I did nest the anchor text and dropdown icon last week to resolve our pass issue of having a dropdown menu with an href="#", did I create this issue? or is it more of the menu being nested inside of a row?
