### ISSUE TITLE
CMS: Gallery - Links with the same name must have a similar purpose

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#493]
https://utsa.dubbot.com/sites/632ca47e7e251f00019d8e30/pages/633dfef2ef9d941abf06510b

Add some computed aria-labels to avoid repeating link output for gallery items (on a.popup-gallery)

https://utsa-asc.github.io/college-dls/components/preview/gallery--default.html

**Comment by lalov1** [comment]
I could give this one a look.

**Comment by lalov1** [comment]
I'll add the `aria-placeholder` attribute, but I was hoping Sean would go through all the images and add alt text. It is coming up with an error because all the images have "Placeholder" as the alt text because I don't know what some images are.
