### ISSUE TITLE
DLS: Bootstrap Upgrade 5.2.3 > 5.3

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#500]
Uriel and I watched a presentation on implementing dark mode and thought it might be something cool we could do. 

Here is a link to the presentation:
https://events.highedweb.org/heweb22/session/1082486/going-dark?i=X8M63nTeFKHHrALIrFzUlAZHXISTa3HO

MDN article on what they're doing:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Articles: 
- https://atmos.style/blog/dark-mode-ui-best-practices
- https://ryanfeigenbaum.com/dark-mode/

**Comment by garza-utsa** [comment]
Looks like there will be built-in support with BS 5.3, worth experimenting with and maybe seeing if we can customize these themes:
https://getbootstrap.com/docs/5.3/customize/color-modes/

**Comment by garza-utsa** [comment]
This is a SMART goal level task open for the taking =)

**Comment by garza-utsa** [comment]
updated to complete, we have a different PR for dark-mode
