### ISSUE TITLE
CMS: Action card links not working

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#511]
![Image](https://user-images.githubusercontent.com/7785251/199324660-3abe1bba-2f75-4511-9f13-1abfddc2c622.png)

**Comment by garza-utsa** [comment]
I think these should be working now after the action-group stuff I completed yesterday, but let me know if they are not rendering the buttons still

**Comment by lalov1** [comment]
I added a couple of other checks since it looks like it wasn't checking to see if a link was there.
