### ISSUE TITLE
CMS: Links getting output even when "No Link" is selected

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#519]
Example page:

https://walle.it.utsa.edu/entity/open.act?id=5897236781736a2d3d00f35cb9797db3&type=page

https://klesse.utsa.edu/faculty/profiles/painter-frank.html

Outputs a URL for "Personal Website" even tho the data definition is set to "No Link":

<img width="487" alt="Screenshot 2022-11-09 at 2 01 44 PM" src="https://user-images.githubusercontent.com/16828076/200929447-d91db10f-10ee-4b7d-bc9f-7099bf2b8150.png">

<img width="800" alt="Screenshot 2022-11-09 at 2 02 14 PM" src="https://user-images.githubusercontent.com/16828076/200929531-5b8b6dd9-17c1-49b6-a74a-2d7e0bf827d0.png">

Looks like the format logic is not looking at type, and only if there is a label.  The existing link data is from an old profile (copied profile page?).  https://sites.google.com/view/omarabbaas/home

**Comment by garza-utsa** [comment]
updated conditional after #linkData:

`                                #if(!$_PropertyTool.isEmpty($linkLabel) && $linkURL.length()>8 && $linkType != "no link")
`

**Comment by lalov1** [comment]
Is it okay to close this issue?
