### ISSUE TITLE
DLS: Footer year out of date

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#549]
https://utsa-asc.github.io/college-dls/components/detail/global-footer.html

**Comment by DebarshiMondal-06** [comment]
Hi, @lalov1  will work on this issue, what I've understood you want to change the year in global-footer.html file right?

**Comment by lalov1** [comment]
@DebarshiMondal-06 We were going to let one of our students work on this issue. I'm sorry!

**Comment by lalov1** [comment]
I don't see the updated year. Maybe this got reverted somehow.

**Comment by prd409-utsa** [comment]
@lalov1 I assigned to myself but then saw your comment about Student Worker doing it. I would be a good one for Ben.

**Comment by lalov1** [comment]
@prd409-utsa The comment was from a while back, so feel free to make the change.
