### ISSUE TITLE
DLS: Main navigation overflowing on last top nav link at certain resolutions

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#559]
This is happening on my laptop screen on the HCAP website. 

![Image](https://user-images.githubusercontent.com/7785251/216663163-81204c0e-7554-422b-8bfc-2142b666fb74.png)

**Comment by garza-utsa** [comment]
do we need to allow for word wrapping? or suggest a limit on text side for each item (this might be unreasonable for smaller screen sizes)

**Comment by lalov1** [comment]
Maybe we could change the `.dropdown-item` to `white-space: normal` for this breakpoint.
