### ISSUE TITLE
Card - News Card

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#56]
move over markup HTML from dev site into college-dls

PL Names sheet:
https://utsacloud-my.sharepoint.com/personal/kyra_kauschel_utsa_edu/Documents/PL%20Names.xlsx?web=1

SS Ref:
https://development.simpsonscarborough.com/utsa/card-tiles.html#news-card-component

**Comment by prd409-utsa** [comment]
Branch: [sprint-02-news-card](https://github.com/utsa-asc/college-dls/tree/sprint-02-news-card)

**Comment by prd409-utsa** [comment]
SS DLS:  [News Card Component](https://development.simpsonscarborough.com/utsa/card-tiles.html#news-card-component)

**Comment by garza-utsa** [comment]
closed by PR #120
