### ISSUE TITLE
DLS: a11y error with tab component

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#562]
dubbot is reporting an error with our tab component, example live page here:

https://utsa.dubbot.com/sites/632ca47e7e251f00019d8e30/pages/6362ebc22593033cc743f294

2 critical errors with our aria labels and 1 serious with our use of list items

<img width="2070" alt="dubbot-tab-li-errors" src="https://user-images.githubusercontent.com/16828076/217034717-3353d54f-0dfc-4015-8c58-c588284acb96.png">

**Comment by lalov1** [comment]
We may need to make the code closer to the info in the docs: 
- https://getbootstrap.com/docs/5.2/components/navs-tabs/#regarding-accessibility
- https://getbootstrap.com/docs/5.2/components/navs-tabs/#javascript-behavior
- https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
