### ISSUE TITLE
DLS: Image requirements need to be added to all components that have an image

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#566]

**Comment by lalov1** [comment]
@ bennie-aranda - Could you handle this one? I didn't start working on this, but it might be good for you. 

Could you add the Media Requirements to the notes of all components with images? Here is an example of one already completed:
https://utsa-asc.github.io/college-dls/components/detail/profile-card--default.html

You can find a lot of the placeholders here: 
https://walledev.it.utsa.edu/entity/open.act?id=420d837d81736a1b55fcab75ae19a99d&type=folder

Please feel free to reach out to me or @Uri-E with any questions.

**Comment by bennie-aranda** [comment]
So the changes would need to be made via vs code? I am currently on 01-profile-card and I see two hbs files for profile-card. I am assuming I would put the media requirements in there ?

**Comment by bennie-aranda** [comment]
oh okay got it I was looking at the wrong files. Thank you for pointing me in the right direction!

**Comment by bennie-aranda** [comment]
I noticed a typo on the "Image should be no larger and 300kb (kilobytes)"

did you want me to change it to "no longer than"?

**Comment by bennie-aranda** [comment]
**larger

**Comment by bennie-aranda** [comment]
[like]  Bennie Aranda (student) reacted to your message:
________________________________

**Comment by lalov1** [comment]
I think it's fine since it's referring to the above since it's a sub-bullet: 
<img width="1159" alt="Screenshot 2023-10-20 at 12 11 04 PM" src="https://github.com/utsa-asc/college-dls/assets/7785251/ac70f614-b850-4c07-8419-51ff4b2b31a6">

The 300kb is a little large, so you should ask @ Uri-E if it should be less than that.

**Comment by bennie-aranda** [comment]
oh okay got I just thougth maybe it was a typo
