### ISSUE TITLE
DLS: Add Back to Top indicator

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#570]
I noticed the Future website has a Back to Top button indicator and thought it would be a good enhancement for us too!

![Image](https://user-images.githubusercontent.com/7785251/220130340-75bf788d-b137-4487-9f43-2ac101c7eb73.png)

**Comment by garza-utsa** [comment]
this should be mocked-up inside the DLS first.  The colors for this arrow on future.utsa.edu seem a little off/non-standard?
