### ISSUE TITLE
DLS: unordered and ordered lists might be better scoped to the body of the page instead of using a class

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#577]
- https://utsa-asc.github.io/college-dls/components/detail/unordered-list.html
- https://utsa-asc.github.io/college-dls/components/detail/ordered-list--default.html

**Comment by garza-utsa** [comment]
think we need more context and or use cases for this type of change, is the intention to just have these be the default styles w/o any class names or do they need to be scoped instead to the div.content on a page?

**Comment by lalov1** [comment]
I was thinking they would be the default for all ul or ol's. It might be nice to target the `.page-text-wrapper`, so the ul/ol's aren't so tight by default.

**Comment by garza-utsa** [comment]
pinging @Uri-E  on this one for some input, do you think this is ok to have as part of our default list styles? or scoped to `.page-text-wrapper`?

**Comment by Uri-E** [comment]
It'd be nice to have it be the default list styles, and we should probably specify for lists within the page wrapper just in case it causes the nav or something else to go bananas.
