### ISSUE TITLE
CMS: Display Name was not imported, so Title has Cascade code

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#578]
![Image](https://user-images.githubusercontent.com/7785251/227344581-1782a5ac-f9ba-4873-913c-140829f6a3b2.png)

**Comment by garza-utsa** [comment]
This should be fixed with the updated title and meta formats

**Comment by lalov1** [comment]
I published the profiles, and it looks like the Display Name is still blank. This is causing the title tag to have Cascade code in it. Should we pull from the Title metadata if the Display name isn't available?

**Comment by garza-utsa** [comment]
orz, let me double check I copied the right formats from the Klesse stuff last week...

**Comment by garza-utsa** [comment]
ok, switching to $_PropertyTool.isEmpty() checks did the trick I think, republishing now
