### ISSUE TITLE
Content Group - News Group

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#58]
move over markup HTML from dev site into college-dls

PL Names sheet:
https://utsacloud-my.sharepoint.com/personal/kyra_kauschel_utsa_edu/Documents/PL%20Names.xlsx?web=1

SS Ref:
https://development.simpsonscarborough.com/utsa/listing-component.html#blog-news-component

**Comment by prd409-utsa** [comment]
branch: sprint-02-news-group

**Comment by prd409-utsa** [comment]
In SS DLS: 5.8.5 Listings / [Blog/News Listing Component](https://development.simpsonscarborough.com/utsa/listing-component.html#blog-news-component)

**Comment by prd409-utsa** [comment]
The Grey Example HTML on SS site does not include the class for the gray background that should wrap around the entire _<div class="news-card">_, 
I added: 
1: _<div class="news3-card-laout-grey position-relative">_  to  "Gray Example"  in  **news-group.hbs** file.
2: selector  _news3-card-laout-grey_  to the  **news-group.scss**  file.

**Comment by prd409-utsa** [comment]
The Grey Example HTML (that is copied with button) on SS site does not include the class for the gray background that should wrap around the entire <div class="news-card">,


So, I added: 
1: _<div class="news3-card-laout-grey position-relative">_  to  "Gray Example"  in  **news-group.hbs** file.
2: selector  _news3-card-laout-grey_  to the  **news-group.scss**  file.

**Comment by garza-utsa** [comment]
feel free to use the existing defined background colors (like the lightgrey-bg):

https://utsa-asc.github.io/college-dls/components/detail/background-colors.html

**Comment by garza-utsa** [comment]
closed by PR #120
