### ISSUE TITLE
CMS: Rowdylink integration for the events calendar

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#581]

**Comment by lalov1** [comment]
@garza-utsa It does look like I'm getting the timeout error, so UTS might need to whitelist Rowdylink for Walle and Walledev:
https://walledev.it.utsa.edu/entity/open.act?id=f7bdc36d81736a1b1f3ee033c8f7bdf7&type=block

**Comment by garza-utsa** [comment]
example feed from Sean: https://rowdylink.utsa.edu/organization/coessc/events.rss

no word yet on the firewall request...

**Comment by garza-utsa** [comment]
@lalov1 looks like rowdy link URLs are now accessible from walledev, I think we can finally test this one and hopefully close this one out

**Comment by lalov1** [comment]
It looks like it isn't timing out, but the events aren't showing on the calendar. The events are being added to the JS, so there has to be something else going on: 
![Image](https://github.com/utsa-asc/college-dls/assets/7785251/43705cc0-9ad3-43c3-8e3a-e71b26d5048a)

I'll continue to investigate.

**Comment by lalov1** [comment]
I got it to work, but the setting is only two days out, according to support. I'm still waiting for Analicia to adjust the settings. This is the info I got back from support: 
_Checking into the Data Sharing section found on the Admin side under the "Configure" drop-down, I was able to see that your RSS feed is set to only look 2 days into the future when displaying events. You can set that range up to 100 on that page, so all the public events in that timeframe will be displayed.
 
[https://rowdylink.utsa.edu/admin/customization/dataSharing](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Frowdylink.utsa.edu%2Fadmin%2Fcustomization%2FdataSharing&data=05%7C02%7Clallo.vigil%40utsa.edu%7C5935858001df4f04863408dc44f00e38%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C638461045052849703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Sk4%2Bv1U7IGCtpJdsPSUgIqGG8slbnD0REeIry9tlwjw%3D&reserved=0) 
 
If you have any questions, please let us know.
 
Best,
Justin Johnson
Product Support Coordinator, Global Support
Anthology

[support@campuslabs.com](mailto:support@campuslabs.com)
(716) 270-0000

Need help? Visit our Support Site! [https://campuslabs.zendesk.com/hc/en-us](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcampuslabs.zendesk.com%2Fhc%2Fen-us&data=05%7C02%7Clallo.vigil%40utsa.edu%7C5935858001df4f04863408dc44f00e38%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C638461045052865835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=hZGRWGfLO1MADLZ7G%2BuAvGyGBjgzsROFtWv%2F1bc4sPU%3D&reserved=0)_

**Comment by lalov1** [comment]
This has been completed, so I'm closing this out.
