### ISSUE TITLE
CMS: News template needs OG meta tags

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#588]
I do not see the OG meta tags that are in other news articles on the provost news site:
`
<meta content="Rebecca Luther" property="og:author"/>
<meta content="https://www.utsa.edu/today/2023/images/bold-scholars_780.png" property="og:image"/>
<meta content="350" property="og:image:height"/>
<meta content="780" property="og:image:width"/>
`

Also, it looks like there is some Cascade code for the publish time:
`<meta content="${start}" property="og:article:published_time"/>`

**Comment by garza-utsa** [comment]
${start} should've been ${_start}.  adding a conditional on content type for blog to output the image1 as the meta go:image. Need to go back and do the same for author

**Comment by garza-utsa** [comment]
updated with author info on blog posts
