### ISSUE TITLE
CMS: UTSA Today articles don't show up on news pages

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#594]
I created a reference to the article, but it isn't showing up on the index page: 
https://walle.it.utsa.edu/entity/open.act?id=2121df3c81736a2d310ada95233c722d&type=reference

**Comment by garza-utsa** [comment]
reference items should be showing up now, tested on WALLEDEV and WALLE

**Comment by lalov1** [comment]
@garza-utsa I added one for 2023. Should it filter to the News Group component? Also, is there a way to tag it so it shows in another section of the site?

**Comment by garza-utsa** [comment]
hrm, all the filter components use query API which will not pick up references, so I don't think we can support that, however, they can pick any asset type when using a manual news group
