### ISSUE TITLE
CMS: Active link isn't inside Cascade

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#604]
It seems like the Active link is in the DLS, but not in the CMS. 
https://utsa-asc.github.io/college-dls/components/detail/side-navigation--default.html

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/b42198a0-a568-462f-bc20-33eec5f36e45)

**Comment by garza-utsa** [comment]
this **should** be do-able in our side-navigation format (College-PROTOTYPE/_cms/formats/components/sideNavigation)[https://walledev.it.utsa.edu/entity/open.act?id=d1f6412a81736a1b3be11e0611458b58&type=format] by comparing the path/link output for an anchor with the $currentPage.path/link.  Consideration may need to be taken when on in index.html page...

**Comment by garza-utsa** [comment]
updated [sideNavigation](https://walledev.it.utsa.edu/entity/open.act?id=d1f6412a81736a1b3be11e0611458b58&type=format) on WALLEDEV.  Example active page example at: https://walledev.it.utsa.edu/entity/open.act?type=page&id=d1f6347981736a1b3be11e06539d13c9&confId=d1f63d2681736a1b3be11e063d8b1873

**Comment by garza-utsa** [comment]
let me know if this fits the bill @lalov1

**Comment by lalov1** [comment]
Looks good to me! I know you mentioned that consideration may need to be taken when on the index.html page, but I think it looks fine: https://walledev.it.utsa.edu/entity/open.act?type=page&id=ca92bc6c81736a1b3773764cb2ede431&confId=d1f63d2681736a1b3be11e063d8b1873

**Comment by garza-utsa** [comment]
moved to WALLE, going to close, but feel free to reopen if we see any issues pop-up

**Comment by garza-utsa** [comment]
per @Uri-E , need to not active-link the sidebar menu header element (.nav-item .heading)
