### ISSUE TITLE
Angle Button hover color on colored backgrounds?

### ISSUE THREAD

**Issue by jampafoo** [utsa-asc/college-dls#608]
When in blue-bg, orange-bg and grey-bg containers, angle buttons will sometimes disappear because they do not have specific hover styles set for those backgrounds! 

Would be swell if they could match the hover colors of regular buttons as seen here: https://utsa-asc.github.io/college-dls/components/detail/button.html

**Comment by lalov1** [comment]
@jampafoo - I think this has been updated, but I might be wrong: https://utsa-asc.github.io/college-dls/components/detail/call-to-action-buttons--orange-2up.html

**Comment by jampafoo** [comment]
@lalov1 these styles are too specific in that the Container must be .headline-text-btn-wrapper.  I have reduced specificity to just .orange-a11y-bg and .blue-bg.

**Comment by garza-utsa** [comment]
may need to replicate the template for regular buttons to angled buttons to more clearly see the issue, but for the button to know which color the background is, the wrapping container will need to have a color assigned, see the working example on regular buttons:
https://utsa-asc.github.io/college-dls/components/detail/button.html

**Comment by jampafoo** [comment]
@garza-utsa feel free to adjust - I have added css and changes to the angled button templates. Example from preview environment: https://utsa-asc.github.io/college-dls/608-angle-button-hover-color-on-colored-backgrounds/components/detail/angled-button--large.html

**Comment by garza-utsa** [comment]
changes added, waiting for the team to review, thanks for the issue, @jampafoo !
