### ISSUE TITLE
CMS: Events calendar repeating and is wrong date for recurring event

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#612]
It looks like the event is repeating. It seems like it's running through both if statements in the eventFilter, so not sure if we should make it an ifelse:
```
## normal case            
#if (($eventStart > $filterStartDate) && ($metaStart < $filterStartDate))
    ## adding: ${etitle}
    #set( $_void = $finalEvents.add($e))
#end
## overlapping case
#if (($eventEnd > $filterStartDate) && ($metaStart < $filterStartDate))
    ## adding: ${etitle}
    #set( $_void = $finalEvents.add($e))
#end
```

Also, it looks like there may be a mistake in the calculation of the event since it's coming up on the 30th, but the next occurrence should be the 21st.

I set up a mirror of the event Amanda has here:
https://walledev.it.utsa.edu/entity/open.act?type=page&id=bf8423ae81736a1b062280beee628ad4&confId=2089375281736a1b6f1791c008793205

**Comment by garza-utsa** [comment]
hmm, yeah, and if/else should take of this, the calculation bug tho would be somewhere else?  time for some debugging action via html comments! =)

**Comment by garza-utsa** [comment]
still have to account for the featured color flag, but let me know if this looks more correct:
https://walledev.it.utsa.edu/entity/open.act?id=14d7d34b81736a1b5bc85d70f7834740&type=page

**Comment by lalov1** [comment]
It looks like the dates still aren't matching up with what is on the calendar:
https://walledev.it.utsa.edu/entity/open.act?id=9d017af381736a1b04b1b96330b9a2fc&type=page

**Comment by garza-utsa** [comment]
arg, not sure why I was thinking 8/30 was a correct date, hmm, where is this calculation going wrong, I'm using the same #FindNextWeeklyOccurrence macro...

**Comment by lalov1** [comment]
The calculation was correct since the next event was seven days out, but it was starting on the 30th and not the 28th.

**Comment by garza-utsa** [comment]
@lalov1 feel free to close this if you can verify my fix is correct now =)

**Comment by lalov1** [comment]
Looks good to me!
