### ISSUE TITLE
CSS: Increase Container Padding for Mobile

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#614]
Can we please incrase the mobile padding on the container div. When viewing the site on the phone, the content visually is very close to the edge of the screen

I recommend we upping the value .5 to .99. Thank you!

![Uploading Screen Shot 2023-08-23 at 2.19.02 PM.png…]()

**Comment by garza-utsa** [comment]
image did not upload, could you also please find an example from the dis [reference pages](https://utsa-asc.github.io/college-dls/components/detail/department-home-page.html)

**Comment by kgarza-utsa** [comment]
According to inspect, th styles are in the site.css. can we change the padding-left and padding-right to .99 instead of .5?

.container, .container-fluid, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl {
    --bs-gutter-x: 1.5rem;
    --bs-gutter-y: 0;
    margin-left: auto;
    margin-right: auto;
    **padding-left: calc(var(--bs-gutter-x)*.99);
    padding-right: calc(var(--bs-gutter-x)*.99);**
    width: 100%;}

Before
<img width="518" alt="Screen Shot 2023-08-23 at 10 46 07 PM" src="https://github.com/utsa-asc/college-dls/assets/107521898/09785882-86b3-4c68-ab5e-3129d4639986">

After
<img width="516" alt="Screen Shot 2023-08-23 at 10 43 41 PM" src="https://github.com/utsa-asc/college-dls/assets/107521898/330d9010-ffdc-4cf0-9fb0-27fcab9d0862">

Before
<img width="498" alt="Screen Shot 2023-08-23 at 10 45 43 PM" src="https://github.com/utsa-asc/college-dls/assets/107521898/a563101e-5b36-465b-9863-003c6c57ad5b">

After
<img width="502" alt="Screen Shot 2023-08-23 at 10 45 28 PM" src="https://github.com/utsa-asc/college-dls/assets/107521898/58b45e95-b7e6-48f9-893a-ab84388b3070">

**Comment by garza-utsa** [comment]
This will need to be done via the documented SASS variables for bootstrap so it translates over correctly to all our breakpoints. See: https://github.com/twbs/bootstrap/blob/cb021439c683d9805e2864c58095b92d405e9b11/scss/_variables.scss#L367

**Comment by kgarza-utsa** [comment]
thank you!

**Comment by garza-utsa** [comment]
for testing @kgarza-utsa this PR #638 :
https://utsa-asc.github.io/college-dls/614-css-increase-container-padding-for-mobile/components/detail/college-home-page.html
