### ISSUE TITLE
CMS: if no news items are available do not show the section

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#616]
![Image](https://user-images.githubusercontent.com/7785251/266680624-4b0e4d4f-41de-4e55-bebb-f66404f03405.png)

**Comment by garza-utsa** [comment]
let's also use [system-view:internal]This appears inside Cascade.[/system-view:internal] in this format to give a visual message within cascade when there are no results to display, letting the user know it's the content and not cascade preventing this component from rendering

**Comment by lalov1** [comment]
I've added it to Walledev: https://walledev.it.utsa.edu/entity/open.act?id=5acab03d81736a1b7aa9d523a5a123ba&type=page

Let me know if this looks okay, and I'll move it to Walle.

**Comment by garza-utsa** [comment]
👍

**Comment by lalov1** [comment]
Changes made to Walle
