### ISSUE TITLE
DLS: Label doesn't match up for form elements

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#620]
I noticed some of the labels for the form elements don't match up to accessibility standards. 
https://utsa-asc.github.io/college-dls/components/detail/form--default.html

```
<label id="filterDegree" class="d-none">Filter By Degree Type</label>
 <select class="js-example-disabled-results" aria-labelledby="filterDegree">
<option>Filter By Degree Type</option>
</select>

```
Should be:

```
<label for="filterDegree" class="d-none">Filter By Degree Type</label>
 <select id="filterDegree" class="js-example-disabled-results" aria-labelledby="filterDegree">
<option>Filter By Degree Type</option>
</select>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by garza-utsa** [comment]
we've never used any of the SS deliverables around forms in implementation, so this is probably the first time this markup is getting a good review/clean-up.
