### ISSUE TITLE
CMS: Tags supported page for event list

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#622]
COLFA suggested we have an event list similar to the news pages that were developed for COS: https://sciences.utsa.edu/mathematics/news.html

**Comment by Uri-E** [comment]
Using the events list with image like this?

https://xd.adobe.com/view/ddcade9e-8695-4f73-836d-ef0eb2e7b17c-8899/

**Comment by garza-utsa** [comment]
still needs DLS implementation

**Comment by garza-utsa** [comment]
added to walledev and walle, 1/26

https://walledev.it.utsa.edu/entity/open.act?id=42bcc76e81736a1b36f691ba887da72b&type=page

https://walle.it.utsa.edu/entity/open.act?id=467d552781736a2d31c2e14be5e9cede&type=page
