### ISSUE TITLE
CMS: Filtered calendar on a department page

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#624]
Departments asked for a calendar view for only their events. #622 might be a temporary fix until we get this going.

**Comment by garza-utsa** [comment]
let me know if the Event List By Tag Page will work, example usage on colfa right now:

https://walle.it.utsa.edu/entity/open.act?id=4664266581736a2d31c2e14bc91b9d5b&type=page

**Comment by lalov1** [comment]
I switched the tag to "music" since there are more events, but it's showing events that already occurred:
<img width="1359" alt="Screenshot 2024-02-07 at 9 28 53 AM" src="https://github.com/utsa-asc/college-dls/assets/7785251/2f299b13-2590-4e3b-8707-005d592242e9">

Most of their events don't have a Start and End Time since we didn't want them to fall off the calendar. 

Also, this might be a separate issue, but it seems like the items aren't falling off the event group too:
<img width="1359" alt="Screenshot 2024-02-07 at 9 31 53 AM" src="https://github.com/utsa-asc/college-dls/assets/7785251/d42fae02-45d8-4fc1-b06b-f65fc81b820a">

I thought this was working since the event should end by the Event End Date.

**Comment by garza-utsa** [comment]
are these events with multiple occurrences?

**Comment by lalov1** [comment]
No, they are singular events. Here is an example of one:
https://walle.it.utsa.edu/entity/open.act?type=page&id=ef39698181736a2d2b8777b2596429a4&confId=ed11492b81736a2d0da76306faace4bf

I think it's because they're missing a Start Date and End Date: 
<img width="872" alt="Screenshot 2024-02-07 at 11 45 16 AM" src="https://github.com/utsa-asc/college-dls/assets/7785251/83968bf1-1b4f-4350-a4a5-247dcbbddd8d">

Also, the event group block doesn't have a Filter Start Date:
<img width="476" alt="Screenshot 2024-02-07 at 11 47 54 AM" src="https://github.com/utsa-asc/college-dls/assets/7785251/839c13d5-cf3b-4027-904b-0237f65ae0e8">

It says it's required in the help text, but technically it isn't required, right? You wouldn't want to go back and keep adding a filter date.

**Comment by garza-utsa** [comment]
if no filter start is given, the current date (today) is used

**Comment by garza-utsa** [comment]
looks like these are working now, going to close, but feel free to re-open if I missed something
