### ISSUE TITLE
CMS: Events not showing when spanning multiple dates

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#627]
Nick reported the following events not being shown on the Arts website:
- https://colfa.utsa.edu/events/2023/09/jesus-benavente-alicia-eggert.html
- https://colfa.utsa.edu/events/2023/09/xxi-biennial-faculty-exhibition.html

**Comment by lalov1** [comment]
I got this working by adding a filter date to the events block:
https://colfa.utsa.edu/art/

I updated the following code, but didn't want to release it when I'm leaving: 

```
        #if (($eventStart > $filterStartDate) && ($metaStart < $filterStartDate) || ($eventEnd > $filterStartDate))
            ## adding: ${eo.get("title")}
            #set( $_void = $finalEvents.add($eo))
        #end

```

Also, I'm proposing commenting this if block in the frequency Once since the code above covers it too:

```
                ## #if ($sCal.compareTo($begin) >= 0)
                    #set ($occurrenceData = {})
                    #set ($_void = $occurrenceData.putAll($eventData))
                    #set ($occurrenceData.sdate = $sDate.getTime())
                    #set ($occurrenceData.edate = $eDate.getTime())
                    ## <!-- adding to eventOccurences (ONCE): $occurrenceData -->
                    #set ( $_void = $eventOccurrences.add($occurrenceData) )
                ## #end

```

**Comment by lalov1** [comment]
I released the code to production since COLFA was having more problems with events that spanned multiple days. Should be fixed now.

**Comment by garza-utsa** [comment]
👍
