### ISSUE TITLE
CMS: remove title/displayname from profile-block

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#648]
Rely more on a full name field within the block.  This is a major DataDefinition change and care must be taken not to lose data.

- [ ] update data definition, add field
- [ ] migrate data from faculty metadata set to profile-block field
- [ ] update formats to use the new field instead of metadata set field when outputting profile cards
- [ ] update formats to use the new field instead of metadata on profile pages
- [ ] verify, verify, verify
- [ ] update faculty metadata set for profile-blocks (remove inline displayName, Title)
- [ ] update faculty metadata set for profile-pages (remove inline displayName, Title)
- [ ] verify, verify, verify

**Comment by garza-utsa** [comment]
correct, I think we should use a single field (that lives in the profile block DD) for all these locations, thus removing the need for the extra metadata fields and hopefully resolve any confusion on where to go to change the name

**Comment by lalov1** [comment]
- I created a new metadata set with the Display Name inline and added help text, so the user knows what is referenced on the page: https://walle.it.utsa.edu/entity/open.act?id=5fee3c3081736a2d5c519567f34bf163&type=metadataset
- The profile now pulls the title for the h2 and not the block Display Name. 

Changes have been deployed to Walledev and Walle. 

Hopefully, this will clear anything up for the users.
