### ISSUE TITLE
CMS: Active link doesn't work if link has a bookmark after it

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#664]
I noticed if you have a link with an anchor tag in the nav it won't show the active class. 

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/15da3f7b-c0cc-4dcc-b4bb-791f2474e14e)

**Comment by garza-utsa** [comment]
@Uri-E What is the correct behavior for a sidebar with multiple links to the same pages (some with anchors?):

https://new.utsa.edu/COLLEGE-PROTOTYPE/prototype/active-link-test/#anchor-test

Should both Test Pages be "active"?

**Comment by Uri-E** [comment]
Hmm, I don't think it's necessary to do both, it'd just be a block of orange then. In our site, If it's anchor links I think the landing page should be what is active. The user is going to have to scroll to the top to see the navigation anyway. It'd be different if the side nav followed them to the section, but it doesn't :P

**Comment by garza-utsa** [comment]
going to label this one as out of scope, the only way to change the anchor link to active would be client side on javascript, i.e.- the right "page" (index.html) is getting tagged as active, just not the jump anchor link as that is not a publishable target
