### ISSUE TITLE
DLS: Replace image with font-awesome icon for Events List component

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#699]
https://utsa-asc.github.io/college-dls/components/detail/event-card--horizontal.html

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/4e7a141b-8a43-492e-8e8e-56724472b330)

Also, look for any other images being used where font-awesome icons could be used instead.

**Comment by garza-utsa** [comment]
For anybody daring, this would be a mashup of the existing angled button css with the geometry of the image mask clip css:

[Angled Button](https://utsa-asc.github.io/college-dls/components/detail/angled-button--default.html)

[Mask Clip](https://utsa-asc.github.io/college-dls/components/detail/misc.html)
