### ISSUE TITLE
CMS: Faculty listing pages may result in duplicate office, telephone anchors

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#718]
will need to prefix profile person's name with office and phone location outputs in aria label:  

"210-..." becomes: "John Doe's Phone: 210-"

I vaguely remember doing this with the SDS faculty group output...maybe this has already been done?

<img width="2134" alt="Screenshot 2024-01-17 at 12 32 10 PM" src="https://github.com/utsa-asc/college-dls/assets/16828076/59809c25-c350-4715-9cf6-9eb9ed871023">

https://utsa.dubbot.com/sites/5eea4b24482faf49264a90d7/pages/65a180085be47de24f3ed97f

**Comment by garza** [comment]
added "<name> - Phone: " prefix to the aria-label for phone and a similar version for the email

**Comment by garza-utsa** [comment]
migrated format to WALLE, look like the error in dubbot is resolved
