### ISSUE TITLE
CMS: Faculty directory for colleges should have toggle to have the ability to do a 4-up view

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#725]
Sean had requested the 4-up view for their college. Business has the toggle, but the other schools still need to include it. 

https://walle.it.utsa.edu/entity/open.act?id=5895f32e81736a2d3d00f35c4b123ccf&type=page

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/768f572f-6351-4c81-8a9f-3047b868e3bc)

**Comment by garza-utsa** [comment]
drop down should be present on the regular faculty index pages now

https://walle.it.utsa.edu/entity/open.act?id=fac598f381736a2d1860fc585dcea19c&type=page
