### ISSUE TITLE
CMS: News Group Static should have 6 and 9 Max Items to Show option like Filtered version

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#728]
![Image](https://github.com/utsa-asc/college-dls/assets/7785251/3fe109dd-1f1a-49cb-8ccc-f565ff84bc5d)

**Comment by garza-utsa** [comment]
since it's a static, I think we need to relax the DD max to 9 first, and then add this drop down but change the heading to "Items per row"?

**Comment by garza-utsa** [comment]
oh wait, the faculty-group-filtered only has 3-up and 4-up, static supports 2-up, 3-up, 4-up.  Did we really want to try 6-up and 9-up?  those will be some pretty packed cards

**Comment by lalov1** [comment]
I may have worded it wrong, but this would give the editor the ability to have two rows of six or three rows with nine items.

**Comment by garza-utsa** [comment]
oh, for the static, there should be no maximum set, so the user has to manually add each member, do we still need a max cutoff? this might become confusing to the user if they added 10 people, have the limit set to 9 and then wonder why they aren't seeing someone?

**Comment by lalov1** [comment]
I added this a while back, and I messed up the title because this was for the News Group Static. I did give the user the ability to add more on Walledev, but I still need to add the Max Items to Show since the bottom margin is a little tight: https://walledev.it.utsa.edu/entity/open.act?id=fb43788981736a1b39061c4676cdc861&type=page

**Comment by lalov1** [comment]
It doesn't need the option like you said. I added a `.my-2` like the filtered version has, and it looks like it's displaying correctly:
https://walledev.it.utsa.edu/entity/open.act?id=fb43788981736a1b39061c4676cdc861&type=page

Also, I changed the max to nine articles in the data def.
