### ISSUE TITLE
CMS: Character code is showing in title tag

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#731]
I've noticed the character code is showing in the title of some pages with ampersands or other characters. This is from title being escaped, so I don't know if there is any way around this. 
![Image](https://github.com/utsa-asc/college-dls/assets/7785251/02d6ec46-64ce-4023-b4fa-2f146187ee08)

https://walledev.it.utsa.edu/entity/open.act?id=923d1b3c81736a1b6bf065e1d9394051&type=format

**Comment by garza-utsa** [comment]
hmm, which page is this? it would only be double escaping if the title is actually "&amp;" and not "&"

https://walle.it.utsa.edu/render/page.act?id=58969ce981736a2d3d00f35ca379dc4d&confId=fac5abec81736a2d1860fc5845a50771&demarcate=false&fullscreen=true

**Comment by lalov1** [comment]
https://klesse.utsa.edu/civil-environmental-construction-management/

I wonder if it's because it's escaped at the top, but then escaped at the bottom again.

**Comment by garza-utsa** [comment]
`#import("_cms/formats/global/utilities")
##
#set ( $callingPage = $currentPage.metadata )
#set ( $title = $_EscapeTool.xml($callingPage.title.trim()) )
#set ( $displayName = $_EscapeTool.xml($callingPage.displayName.trim()) )
#set ( $name = $_EscapeTool.xml($currentPage.name.trim()) )
#set ( $fullSiteName = $_EscapeTool.xml($siteSetup.metadata.title).trim() )
##
## title: ${title}
## dn: ${displayName}
## name: ${name}
## $_PropertyTool.outputProperties($currentPage)
## $_PropertyTool.outputProperties($callingPage)
##
#set ( $outputTitle = $displayName )
#if ( $_PropertyTool.isEmpty($outputTitle) )
    #set ( $outputTitle = $title )
#end
#if ( $_PropertyTool.isEmpty($displayName) and $_PropertyTool.isEmpty($title) )
    #set ( $outputTitle = $name )
#end
##
${outTitle} | $fullSiteName | UTSA | University of Texas at San Antonio`
