### ISSUE TITLE
CMS: Sitemap issues

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#734]
The pages are grouped by content type, but I'm not sure if this is valid or if the content types are valid. 
![Image](https://github.com/utsa-asc/college-dls/assets/7785251/9d4a9dea-a6d7-477b-bdcb-0d0c582eca5b)
https://www.sitemaps.org/protocol.html

Also, the faculty profiles aren't showing up for some reason, but I'm unsure if this is by design. 
https://business.utsa.edu/sitemap.xml

Using this [validator](https://www.inspyder.com/free/SitemapValidator.aspx), I'm getting the following errors:
- The 'site' attribute is not declared.
- The element 'urlset' has invalid child element 'type'. List of possible elements expected: 'url'.

**Comment by garza-utsa** [comment]
hmm, yeah , program, faculty and gallery are blocks, so there would be no pages returned.  we can probably remove those metadata types from the format

**Comment by garza-utsa** [comment]
removed the content type element and republished:


<img width="799" alt="Screenshot 2024-02-14 at 2 28 06 PM" src="https://github.com/utsa-asc/college-dls/assets/16828076/e702b3e6-e33e-450a-b4e9-6a3e6ae46263">

**Comment by lalov1** [comment]
Looks good! 👍🏽

It might be good to add a robots.txt file to the sites, but we could handle that in another issue.

**Comment by garza-utsa** [comment]
fixed in both walledev and Walle, published to all existing DLS sites
