### ISSUE TITLE
CMS: TinyMCE editor configuration changes

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#742]
creating the issue here so we don't forget about it:

Feel free to add more suggestions via comments, but before I forget, I think the most important right now are:

- limit our valid elements
- remove empty tags and useless tags like span that lack classes
- investigate usage of before/after content for inline user warnings for:
- missing alt tags?
- internal vs. external link warnings?

**Comment by lalov1** [comment]
A couple of things I think that would be helpful would be:
- auto-adding `loading="lazy"`
- The items on [page 13](https://utsacloud.sharepoint.com/:p:/r/sites/vpaa/communications/Shared%20Documents/Web/2024%20Cascade%20Conf%20-%20Videos/Controlling%20WYSIWYG%20content%20CUC24.pptx?d=wa935bd12ed554f8c878ebe8c21120d6f&csf=1&web=1&e=0WZu2s)
-- You see a lot of these errors in the Dubbot reports 
- convert deprecated items to updated tags

**Comment by lalov1** [comment]
Here is the valid elements list: 
`@[class|style|id],#p,-span[!class|!style],-strong/b,-em/i,-h1,-h2,-h3,-h4,-h5,-h6,-blockquote,-div,-pre,-ul[type],-li[value],-ol[reversed|start],iframe[*],br,-figure,-figcaption,hr,table[*],-thead,-tbody,-tr[*],td[*],-th[*],-tfoot,-code,-picture,-source,-script,-style,-sub,-sup,-video,-abbr,-address,-cite,-dd,-dl,-dt,-pre,-svg,-time,-img[!src|alt|width|height|loading=lazy],-a[!href|!name|target|title|rel]`

Please let me know if any items should be added or removed.
