### ISSUE TITLE
CMS: Add link in page when Article Type is link

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#755]
I noticed when the **Article Type** is **Link** and there is no **Teaser** the page is blank with no link: https://sciences.utsa.edu/news/2024/01/05-professor-discovery-new-reality-on-saturns-moon.html

Not sure if we should use the Title or Display Name when the Teaser isn't available. Another option might be a meta redirect.

**Comment by garza-utsa** [comment]
we might also want a way to get to these pages inside the CMS via the internal view rendering

**Comment by garza-utsa** [comment]
CMS blogContent will now fallback to the article title if the linkLabel is empty
