### ISSUE TITLE
CMS: News Group Filtered showing a broken image if the user didn't add a lead photo

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#760]
I could add a fallback image, but I need to know what we want to use. 
![Image](https://github.com/utsa-asc/college-dls/assets/7785251/d0cd15e1-4498-4199-a12b-555a4af72d57)

**Comment by garza-utsa** [comment]
do we want each college to supply a placeholder, or have something defined in college-prototype for all sites to use?

**Comment by garza-utsa** [comment]
oh wait, nvm, we already have one:

https://walle.it.utsa.edu/entity/open.act?id=fac55d2281736a2d1860fc58092557b6&type=file

https://walledev.it.utsa.edu/entity/open.act?id=d1f627d381736a1b3be11e066f0fd77f&type=file

**Comment by garza-utsa** [comment]
would it be nice to also make that the default asset's image1?

**Comment by garza-utsa** [comment]
renamed and web-optimized to jpg (only 12k now)

**Comment by lalov1** [comment]
> would it be nice to also make that the default asset's image1?

We could always ask on Thursday.

**Comment by lalov1** [comment]
The code has been updated: https://walle.it.utsa.edu/entity/open.act?id=45af314881736a2d5c519567bd3132ac&type=format
