### ISSUE TITLE
CMS - Make accordion & tab body content full-width

### ISSUE THREAD

**Issue by prd409-utsa** [utsa-asc/college-dls#761]
Tables within accordions or tabs do not extend to the full width of the content area. 

Example: https://walle.it.utsa.edu/entity/open.act?id=11d3f52e81736a2d7b917f037ecfddfa&type=page&action=edit

This needs to be added to CSS.

<style>
    .accordion-body-content {
         width: 100%;
     }
</style>

<img width="1684" alt="Screenshot 2024-05-01 at 8 31 22 AM" src="https://github.com/utsa-asc/college-dls/assets/92815346/6804ce7c-77e9-475a-927b-6ec9832bbf8e">

**Comment by garza-utsa** [comment]
@Uri-E, before we start changing these, is there a good reason to not have content full width in these components?

**Comment by Uri-E** [comment]
@garza-utsa Hmm... I can't think of any. I'd say proceed enthusiastically until something catches on fire.
