### ISSUE TITLE
DM: site-ankle is missing dark-mode styling

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#775]
![0a866108-1dcd-4d13-9c98-c9f9e93231dc](https://github.com/utsa-asc/college-dls/assets/16828076/fc5ba002-dd2b-482d-8dd9-a61ded785960)

**Comment by garza-utsa** [comment]
👍

**Comment by lalov1** [comment]
This was completed, so I'm going to close it. If I'm mistaken, feel free to re-open it.
