### ISSUE TITLE
DM: Accordion issues

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#780]
I could break this up into separate issues, but here is what I noticed:

- The header probably needs to be something lighter since the contrast with the blue and black seems a little hard to read
  - It seems like the CMS and DLS don't match up, and the CMS h2 has a `blue` class that I don't think belongs 
- Items not in a paragraph need to match the items in a paragraph
- links seem to be white 

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/14eb5d43-cd82-4fa0-add6-b0723d78495a)
https://teachingtest.utsa.edu/academic-technology/digital-tools/simple-syllabus/

**Comment by garza-utsa** [comment]
we might want to compare mark up and make sure our formats are outputting code that matches with the DLS, I know we've made several tweaks in the DLS that were being accomplished in manual code for some of these

**Comment by garza-utsa** [comment]
removed hardcoded blue from according Group macro to get this inline with DSL markup
