### ISSUE TITLE
DLS: event details page a11y error

### ISSUE THREAD

**Issue by garza-utsa** [utsa-asc/college-dls#781]
Reported by ACOB:

https://business.utsa.edu/events/2024/05/chill-zone-may-9.html

white text on light grey background

![1de36f4d-e60c-429b-9af7-e5c3e53f181a](https://github.com/utsa-asc/college-dls/assets/16828076/5b820c55-aa53-4493-b60c-f7945cfa9c4f)

**Comment by lalov1** [comment]
We could open a separate issue for this, but it looks like the calendar has some contrast issues too: 
<img width="1164" alt="Screenshot 2024-05-20 at 10 09 33 AM" src="https://github.com/utsa-asc/college-dls/assets/7785251/425336ab-2086-4d35-a320-374485ad0c08">

**Comment by garza-utsa** [comment]
yeah, looks like the "UTSA UIDP" probably also won't pass contrast

**Comment by garza-utsa** [comment]
the calendar index should be a separate issue, as it looks like we can fix the event details by updating the color mappings to use $grey-b and black text, doing that now in the CMS
