### ISSUE TITLE
DM: Card Title and Card Text low contrast on grey background

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#798]
https://teachingtest.utsa.edu/course-design-development/resources/

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/f7501284-9eab-4726-85c0-e9ca1c37feca)

**Comment by lalov1** [comment]
Something is still up with this one.

**Comment by garza-utsa** [comment]
did you fix the class typo?  cart-text?

**Comment by lalov1** [comment]
Yes, I did.

**Comment by garza-utsa** [comment]
ah ,the grey-bg is at the same level as card, one sec...
