### ISSUE TITLE
DM: Default CTA text has color contrast issues

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#815]
I am not sure what is going on since it looks fine on the branch, but maybe I'm missing something:
![Image](https://github.com/utsa-asc/college-dls/assets/7785251/c3d111ad-f6f1-482f-a0b3-1d1fc97649a2)

https://educationtest.utsa.edu/about/it-services/labs.html

**Comment by garza-utsa** [comment]
yeah, I'm seeing contrast of 4.59 for that button text, which is good enough for AA

**Comment by lalov1** [comment]
This was for the text in the middle: 
<img width="1165" alt="Screenshot 2024-06-06 at 2 31 28 PM" src="https://github.com/utsa-asc/college-dls/assets/7785251/c2ae8b0f-e912-4e11-8a32-5f4b2e8a0929">
