### ISSUE TITLE
DM: Author field not passing color contrast

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#819]
https://hcaptest.utsa.edu/news/2022/11/new-utsa-research-is-informing-saws-discussion-around-tiered-rate-system.html

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/d833ecef-4161-401c-b1e2-12d8d6c2df3c)

**Comment by garza-utsa** [comment]
bah, this is a regression, copied news-details when creating news-listing and did not clean up the styles...
