### ISSUE TITLE
DM: Link List in tabs has blue hover and blue text

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#820]
https://hcaptest.utsa.edu/faculty/business-service-centers/

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/7882fca1-1ccc-42e3-ab88-aa4d9f0d7ed6)

**Comment by garza-utsa** [comment]
blue hover is correct, but text should turn white:

https://utsa-asc.github.io/college-dls/components/detail/type--anchors.html

**Comment by garza-utsa** [comment]
getting a fix in now, but this might be bubbling up an issue with where  resource-list should live in the tree, should it be higher up (smaller organism) with the ul/ol list components to avoid these types of conflicts with larger components?
