### ISSUE TITLE
DM: Link List in accordion has low contrast

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#821]
https://sciencestest.utsa.edu/faculty/postdoc.html

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/f3968e90-a980-4fe7-b649-0d0ac7e4caaa)

**Comment by garza-utsa** [comment]
attacking after #820 is merged

**Comment by garza-utsa** [comment]
just a quick note, those lists on sciencestest are using both resources-list and list-unstyled...
