### ISSUE TITLE
DM: p and ul tags in table cells are not meeting contrast guidelines

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#848]
- https://colfatest.utsa.edu/student/conference.html
- https://sciencestest.utsa.edu/chemistry/research/instrumentation.html
- https://businesstest.utsa.edu/students/academics/graduate-advising.html

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/e303961c-0d8a-4ddf-9791-0eee8a0d798e)

**Comment by garza-utsa** [comment]
resolved by #849
