### ISSUE TITLE
DM: Contrast errors for current day text and previous and current month text

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#856]
https://uctest.utsa.edu/events/

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/35161be1-d143-4fce-8cd5-44361669e5e3)

**Comment by garza-utsa** [comment]
@Uri-E  hmm, the point is to make these dates more subdued as the current month dates are already white text, any ideas?

**Comment by Uri-E** [comment]
Hmm... Oh boy, this one is gonna be a toughie. I need to put on another pot of coffee and give it a good think.

**Comment by garza-utsa** [comment]
since they aren't links, I wonder if there is a decoration like aria attribute we can attach

**Comment by lalov1** [comment]
I think this was fixed.
