### ISSUE TITLE
DM: Faculty slider a11y orange isn't passing color contrast rules on name field

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#859]
https://businesstest.utsa.edu/embrey-program/

![Image](https://github.com/utsa-asc/college-dls/assets/7785251/fbd0408d-08bf-4423-9ef5-b856700f0717)

**Comment by garza-utsa** [comment]
<img width="459" alt="Screenshot 2024-06-25 at 2 32 21 PM" src="https://github.com/utsa-asc/college-dls/assets/16828076/ab60a489-dd7d-45b0-861c-822a87fad9cd">

resolved by #860
