### ISSUE TITLE
DLS: Action button text not displaying correctly for Content Callout with grey background in Dark Mode

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#915]
https://sciences.utsa.edu/chemistry/
![Image](https://github.com/user-attachments/assets/1a202fff-f12b-4db8-ac2a-d443edcd84a9)

**Comment by garza-utsa** [comment]
Please update the component to use the @render buttons so we can test all the buttons, currently it only includes hardcoded default buttons:

https://utsa-asc.github.io/college-dls/components/detail/content-callout--default.html

{{ render '@button--default' }}
{{ render '@button--orange' }}
{{ render '@button--grey' }}
{{ render '@angled-button--default' }}
{{ render '@angled-button--blue' }}
{{ render '@angled-button--large' }}

**Comment by garza-utsa** [comment]
dark mode styles for angled button are also looking for a .buttons-bg-wrapper which is not part of the component (only part of the wrapping view used to display multiple button renderings):

https://github.com/utsa-asc/college-dls/blob/bc6ba360c27d4a1e89cc5f54ebe1861bf042d3f3/components/01-visual-styling/02-button/03-angled-button/angled-button.scss#L198
